### ISSUE TITLE
Publishing to Samsung Apps

### ISSUE THREAD

**Issue by T-bond** [jellyfin/jellyfin-tizen#1]
Hello!

Thanks for your work.
Do you have any plans to publish the application to the Samsung TV Apps store?
So we could just install it from there?
It would make Jellyfin so much usable for the non-tech users.

I can only build it right now in a Docker, as I am using Arch linux and Tizen studio only works on Ubuntu.

**Comment by dmitrylyzo** [comment]
I would also like the app to be available in the Store. But...
I have not yet delved into the details of the publishing process. As far as I understand, will need a UI description, but this is the whole Jellyfin (because it is bundled). So I'm far from ready for this.

**Comment by samuel9554** [comment]
@dmitrylyzo Would you share the .WGT file... I'm not able to build on windows...

**Comment by dmitrylyzo** [comment]
@samuel9554 I think it won’t work out that way. You need to build a WGT with a certificate for your device.

> I'm not able to build on windows...

Have you looked https://github.com/dmitrylyzo/jellyfin-tizen/issues/2#issuecomment-577539092? If something does not work out, write a message in #2.

**Comment by varlesh** [comment]
@samuel9554 Builded version:
https://yadi.sk/d/d9UkK1LGu1Wwbg
1. Istall Tizen Studio with Certificate Manager & Device Manager
2. Create Samsung Account
3. Connect your TV on Device manager (not close it & see your `NAME_TV`)
4. Get Samsung Author & Distributor certificates and save your profile
5. Extract `Jellyfin.zip` and enter to `Jellyfin` directory and open CMD
6. Build WGT with your certificates:
`tizen package -t wgt -o . -- .buildResult`
7. Install it:
`tizen install -n Jellyfin.wgt -t NAME_TV`

**Comment by varlesh** [comment]
@dmitrylyzo Maybe now it's temporrary solution for mostly users? Publish release on GitHub with builded WGT without certificates. It's very comphortable for upgrade - need only download latest wgt - rebuild with certificates and install to TV

**Comment by dmitrylyzo** [comment]
> @dmitrylyzo Maybe now it's temporrary solution for mostly users? Publish release on GitHub with builded WGT without certificates. It's very comphortable for upgrade - need only download latest wgt - rebuild with certificates and install to TV

#13

**Comment by bebbenhorst** [comment]
I need some support 

I followed the github install page and im stuck at the wgt build im a bit confused about the cli of tizen , is this the tizen.bat file ?

anyway when i run the command in the web directory i get  :
tizen build-web -e "." -e gulpfile.js -e README.md -e "node_modules/" -e "package*.json" -e "yarn.lock" tizen package -t wgt -o . -- .buildResult

Error occured during build!
        java.lang.Exception: The specified directory(C:\nieuw\web\jellyfin-web) is not vaild
Total time: 00:00:00.029

what files do i need to copy?


also when i try the above way i got the message:

tizen.bat package -t wgt -o . -- .buildResult
File Not Found
The system cannot find the file C:\Users\bebbenhorst\Downloads\Jellyfin\Jellyfin\\..\..\..\sdk.info.
Error: Could not find or load main class org.tizen.ncli.ide.shell.Main

**Comment by dmitrylyzo** [comment]
@bebbenhorst Yes, under Windows you should have `tizen.bat` (it configures environment, iirc).

> anyway when i run the command in the web directory i get :
> tizen build-web -e "." -e gulpfile.js -e README.md -e "node_modules/" -e "package*.json" -e "yarn.lock" tizen package -t wgt -o . -- .buildResult

These commands (two separate commands) should be executed in `jellyfin-tizen`. But before this you should build `jellyfin-web` with another command.

Specially for Windows https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Windows

**Comment by bebbenhorst** [comment]
Thanks I got the wgt file :)

now I want to go deploy on emulator I opened the program and created an samsung tv 5.5.x86 image but it stays at booting, I see there is an network tab, should i fill in the ip address of my tv ? and connect? and then there is an cli command prompt for the command?
tizen install -n Jellyfin.wgt -t T-samsung-5.5-x86

or can i just insert the command if i got connected to the tv?

thanks in advance!

**Comment by dmitrylyzo** [comment]
> now I want to go deploy on emulator I opened the program and created an samsung tv 5.5.x86 image but it stays at booting

I have not tested the emulator under Windows. You may need to enable CPU virtualization (CPU VT) in emulator settings. Also it may require to install some extra software.
https://developer.tizen.org/forums/sdk-ide/hd1080-tv-virtual-device-stuck-booting-kernel.?langswitch=en&langredirect=1

>  I see there is an network tab, should i fill in the ip address of my tv ? and connect?

Emulator will connect automatically.
For TV, you should enable Developer Mode on it, and then connect from Device Manager.
![device-manager-1](https://user-images.githubusercontent.com/56478732/82127408-f0a14200-97bb-11ea-9e5f-d671de9acd2e.png)

> and then there is an cli command prompt for the command?
> tizen install -n Jellyfin.wgt -t T-samsung-5.5-x86

This is for emulator. But again `tizen.bat` instead of `tizen`.
For TV, you will see its name in Device Manager.

**Comment by bebbenhorst** [comment]
Thanks!
But in stuck again now at installing
I need Tizen 2.3 for installing jellyfin.wgt on my 2015 UJU7000 tv 15TV_STANDARD1

I got unknown platform when I try to connect.

But I cannot find the right files for it, on the samsung site I dont see any download files for 2.3

Anyone got those files?

**Comment by dmitrylyzo** [comment]
> I got unknown platform when I try to connect.

Can't connect through device manager?

**Comment by bebbenhorst** [comment]
I'm connected but i get unknown platform , and i also cannot right mouse button click to permit install applications

**Comment by varlesh** [comment]
package need install on cmd:
`tizen.bat install -n Jellyfin.wgt -t TV_NAME_FROM_DEVICE_MANAGER`

**Comment by dmitrylyzo** [comment]
I have answered in #19
Let's talk about 2.3/2.4 there

**Comment by shaynethiessen** [comment]
Is this going to be published in the store anytime soon? It would make life easier for a lot of people.

**Comment by garrit-schroeder** [comment]
Hello,

I am currently reading through the documentation of Samsung Seller Office. 
I already created an account and trying to gain partner membership. Partner Membership is necessary to publish the app outside of the US.

**Comment by garrit-schroeder** [comment]
@dmitrylyzo 

The partner process is completed now. 

![image](https://user-images.githubusercontent.com/12541078/86917482-6921e080-c125-11ea-9d0c-6b3ebc4f60ec.png)

**Comment by dmitrylyzo** [comment]
> The partner process is completed now.

That's great, of course, but first you had to contact the core team.

**Comment by garrit-schroeder** [comment]
Of course. I am happy to help. Could you please tell me how?

**Comment by anthonylavado** [comment]
@garrit-schroeder By doing this, you've now taken the ID name in two territories and have potentially delayed publishing the app. Please contact me ASAP, information is on my profile.

**Comment by garrit-schroeder** [comment]
I have sent you an email. My apologies for potentially delaying publishing the app. My intention was to help speed up the process because I would really enjoy having that app on my TV.

**Comment by IgnazioW** [comment]
Hi, I just wanted to ask, if there are some news about the publishing? Did you have success. I would be very happy to receive new news. Thank you in advance.

**Comment by michael9dk** [comment]
Besides the 10.7 release (I'm guessing), what issues are preventing the publish?

**Comment by kot7k** [comment]
Hi, 
I'm also very interesed in the app being published to samsung app store or having an easy ways to install it through usb to our tvs.

**Comment by Daivy03** [comment]
> @samuel9554 Builded version:
> 
> * Jellyfin Git 20200418: https://yadi.sk/d/d9UkK1LGu1Wwbg
> * Jellyfin Git 20200418 (with fix remote control #4): https://yadi.sk/d/YAlJfKaACPZqyQ
> 
> 1. Istall Tizen Studio with Certificate Manager & Device Manager
> 2. Create Samsung Account
> 3. Connect your TV on Device manager (not close it & see your `NAME_TV`)
> 4. Get Samsung Author & Distributor certificates and save your profile
> 5. Extract `Jellyfin.zip` and enter to `Jellyfin` directory and open CMD
> 6. Build WGT with your certificates:
>    `tizen package -t wgt -o . -- .buildResult`
> 7. Install it:
>    `tizen install -n Jellyfin.wgt -t NAME_TV`

_When i try to Build WGT in cmd with this command:_

`tizen package -t wgt -o . -- .buildResult`
I got this error:
```
Windows Script Host
Script: C:\Jellyfin\tizen.js
Row: 4
Character: 4
Error: 'console' it's not defined
Code: 800A1391
Origin: Microsoft JScript run-time error
```


_Do you know how to fix this error?_

**Comment by T-bond** [comment]
@Daivy03 please, open a seperate issue, for problems not connected to the current issue, otherwise everybody who is subscribed to it will get a notification about it. Thank you.

**Comment by MBcom** [comment]
Any update on this?

**Comment by michelferia** [comment]
Hi, I would like to built the client and install it on my samsung TV but I'm not able to connect it using the Device Manager. The app is ok as I was able to install it on the emulator without issue.
I think that my TV need a webserver and download the app from it, I was able to install Emby app some time ago using the method described in their website. Maybe my TV is older than 2015, how to know the year/tizen version? any idea?
thanks !

**Comment by HoLuLuLu** [comment]
@michelferia I think this is not the correct issue for that, it could be better to open a new one.
Maybe you can find some information on the type label on the backside of your TV. Otherwise in the "About" (or something like this) section in the settings menu.
First make sure that your TV is in Developer Mode and connected to the same network as your PC. Then open Tizen Studio and Device Manager. If the Device Manager doesn't show your device you can try to add it by using the Remote Device Manager. You can open Remote Device Manager by clicking on the symbol in the middle 
![Device Manager](https://user-images.githubusercontent.com/17492312/105902277-b5c7fd00-601e-11eb-97b3-626463d55071.png)
of the three symbols at the top right of the Device Manager. The symbol looks like a phone connected to a notebook. 
There you can press on the "+" to add a new device. Give it a name of your choice and type in the IP address of your TV (You can find it in the network menu of your TV or look for it in your router). The port should be typed in already (26101).
Best regards ^^

**Comment by michelferia** [comment]
> @michelferia I think this is not the correct issue for that, it could be better to open a new one.
> Maybe you can find some information on the type label on the backside of your TV. Otherwise in the "About" (or something like this) section in the settings menu.
> First make sure that your TV is in Developer Mode and connected to the same network as your PC. Then open Tizen Studio and Device Manager. If the Device Manager doesn't show your device you can try to add it by using the Remote Device Manager. You can open Remote Device Manager by clicking on the symbol in the middle
> ![Device Manager](https://user-images.githubusercontent.com/17492312/105902277-b5c7fd00-601e-11eb-97b3-626463d55071.png)
> of the three symbols at the top right of the Device Manager. The symbol looks like a phone connected to a notebook.
> There you can press on the "+" to add a new device. Give it a name of your choice and type in the IP address of your TV (You can find it in the network menu of your TV or look for it in your router). The port should be typed in already (26101).
> Best regards ^^

Hi @HoLuLuLu 
thanks for your kind msg, yes I did all those step but Tizen says that device not found.
I'm not able to put the TV in develop mode, please let me know if you have the correct forum for that.
thanks very much again
kind regards,
MF

**Comment by michelferia** [comment]
Hi, any update ? Waiting for the app as my kodi add-on does not work... thanks very much !!

**Comment by MBcom** [comment]
@anthonylavado can you say something about the current status?  
thanks in advance

**Comment by Pyrater** [comment]
I was able to build and deploy the app on my 2 samsung tvs. Any line of effort being worked to publish to samsung app store?

**Comment by shaynethiessen** [comment]
> I was able to build and deploy the app on my 2 samsung tvs. Any line of effort being worked to publish to samsung app store?

It's been a year since this issue was opened, so I kind of doubt it...

**Comment by cipitaua** [comment]
after almost two years, could someone at least explain why this issue stalled for so long? is anyone actually interested in releasing JF to the samsung store? otherwise please be straight and mark this as "wontfix"
thank you

**Comment by dmitrylyzo** [comment]
@cipitaua We are volunteers, doing the project in our spare time. Most of the work related to the app is done in `jellifyn-web` repo. In its current state, it probably won't pass Samsung certification.

**Comment by cvium** [comment]
> 
> 
> It probably will not be approved but.... [imgur.com/a/NTkkE0A](https://imgur.com/a/NTkkE0A) Submitted

While I appreciate the enthusiasm, I do not appreciate users going rogue and trying to publish without our consent.  As has been stated before, it's not that we don't have time to publish it, it's that there are quite a few bugs that have to be fixed before it's ready.

**Comment by cipitaua** [comment]
>  As has been stated before, it's not that we don't have time to publish it, it's that there are quite a few bugs that have to be fixed before it's ready.

@dmitrylyzo @cvium everyone here greatly appreciate your work and the effort to get a fully-functional and polished version of JF, to be eventually published on the samsumg store. But since this process is taking years, meanwhile it would be crucial to release the beta version to the users in a way that avoids the complex building procedure which is intended to developers, not users. See also #3 

This would be also useful to test the beta version and provide feedback about the present usability.

**Comment by anthonylavado** [comment]
@cipitaua Call me jaded, but I personally feel that this is super disrespectful and much like an earlier comment in this issue, this could potentially jeopardize even our ability to use the correct app name on the store. In addition it could also cause confusion and delay when publishing.

I get people want this. I understand that people are upset because this is not on the store. I still don't feel that gives you permission to go and create a submission like this. I'm opening a request with our partner manager at Samsung to see just how much this is going to potentially screw things up for us.

I hope you're happy. I'm sorry for my emotional reaction to this, and while I can't do this (and won't), this is the kind of stuff that would make me want to delete this whole repository. This is the kind of thing that makes me want to stop working on open source software.

**Comment by cipitaua** [comment]
> **Edit:** An earlier version of this comment tagged the wrong user. My apologies.

indeed :)

**Comment by DanielVukelich** [comment]
What people need to understand is that there's not much development to be done in this repo.  Most of the real work is going on in the jellyfin-web repo, which then helps move this project closer to completion.

For some use-cases, the TV's built-in web browser might make a suitable alternative until the app is released.  Once jellyfin-web version 10.8.0 is out, it will [fix a bug which causes the TV to enter sleep mode while playing video](https://github.com/jellyfin/jellyfin-web/pull/2781).  Unfortunately, there is still a bug in the WebOS browser itself that [causes subtitles to disappear](https://www.lgwebos.com/topic/7135-new-ui-update-web-browser-bug-with-disappearing-subtitles-lg-c9-etc/?tab=comments#comment-22114) after a few minutes.

**Comment by dkanada** [comment]
We don't particularly mind, but Samsung and LG most definitely will. One of them even has a rate limit on the number of times we can submit in a given time period, and our past attempts to submit to LG have failed for various reasons.

**Comment by pyrater** [comment]
After reading the responses to this thread i would think that this was not open source software.  I mean the front page clearly states "Jellyfin is Free Software, licensed under the GNU GPL. You can use it, study it, modify it, build it, and **_distribute it for free_**, as long as your changes are licensed the same way." I think a line should be added that says only if the powers that be deem what you do approved. Its amazing more people dont want to help.  When the "developers" are insulting people telling them that they have gone rogue (look up the definition) and actively work to try and sink the efforts of people simply trying to feel a need i am shocked the project isn't dead. I will delete the app request with samsung as i dont feel peoples EGO can handle the app getting into peoples hands and wouldnt want more "threats" of people deleting the code or quiting the project over someone trying to help others. Maybe you should all take a hard look at why your VOLUENTEERING for JF and not working on a closed source project Seems like EMBY may be a better fit for some.

**Comment by pyrater** [comment]
https://imgur.com/akg8Hl9  Picture proof since I have been accused of being a a disrespectful rogue

**Comment by anthonylavado** [comment]
This thread has run its course.

I'm going to open a separate issue for tracking progress. Apologies to all for this one last notification.
