### ISSUE TITLE
Cant playback live TV or Recordings

### ISSUE THREAD

**Issue by ajb142** [jellyfin/jellyfin-tizen#106]
I have Jellyfin combined with Tvheadend.

I can stream live TV and TvHeadend recordings fine from other apps and a web browser. When I try to play back with the tizer app, no video is played back and the app gets into a wired state where the screen is black. If I press back enough times I can exit the app and start it again.

Playing back other media appears fine.

I have attached to the app via dev tools, but cannot see any debug in the console. I plan to rebuild the app in debug and try again later.

I am new to the Jellyfin ecosystem so wold be grateful for any tips on how to investigate this further.

The issue does appear to happen on the emulator but is slightly harder to reproduce. Tvheadened recordings play back but live TV does not.

I am really impressed with all aspects of Jellyfin BTW so am happy to help debug this one.

**Comment by dmitrylyzo** [comment]
https://github.com/jellyfin/jellyfin-tizen/issues/104#issuecomment-1038097198
https://github.com/jellyfin/jellyfin-tizen/issues/79#issuecomment-822068324
https://github.com/jellyfin/jellyfin-tizen/issues/46#issuecomment-683747890

> I have attached to the app via dev tools, but cannot see any debug in the console. I plan to rebuild the app in debug and try again later.

Maybe https://developer.tizen.org/forums/web-application-development/devtools-inspector-hangs-blank-screen
`production` version of web has same output in the console, but `development` is obviously better for debugging.

**Comment by ajb142** [comment]
Thanks for the help. I didn't actually get any console log working but I think I did get a resolution.

I found that there was something causing an exception to be thrown server side. I thought this might have been due to the length of the device ID being sent.

Looks like the bug has been fixed on master branch of the server. so I am going to close the ticket.
