### ISSUE TITLE
Physical play/pause remote button

### ISSUE THREAD

**Issue by Nazar78** [jellyfin/jellyfin-tizen#11]
Hi @dmitrylyzo,

Is there possibility to enable the one remote play/pause button? Currently it's only displaying the default buttons hint. Also best if we can extend the buttons usability to the menu/123 button to bring up settings and the .../extra button to many other functions. Although think this is not possible for the left(<<)/right(>>)/up(>|)/down(|<) buttons as they're tied to the UI navigation.

**Comment by dmitrylyzo** [comment]
> Is there possibility to enable the one remote play/pause button?

If you are talking about "Samsung Smart Remote", you can use circle and OK to trigger playback commands when hint is displayed.

> if we can extend the buttons usability to the menu/123 button to bring up settings

I suppose `123` button mostly used for channel switching (useless for app), so it can be used for hamburger menu. Settings isn't a thing that often used.

> the .../extra button to many other functions

`...` button shows hint for color A/B/C/D keys. They can be handled but for what commands :thinking:
Best if we make it customizable. Maybe with some "supported keys" extension for NativeShell.

> Although think this is not possible for the left(<<)/right(>>)/up(>|)/down(|<) buttons as they're tied to the UI navigation.

Again, if you are talking about Smart remote: when hint is displayed, nav buttons are replaced by new buttons. So there is no conflict.

**Comment by Nazar78** [comment]
Yes I'm referring to the One Smart Remote, mine with Netflix and Prime.

> Best if we make it customizable. Maybe with some "supported keys" extension for NativeShell.
Yes highly agree.

I was looking for the keycode for this via `tizen.tvinputdevice.getSupportedKeys()` it wasn't listed but  atlast I found out **10252** is the magic number for the `MediaPlayPause` button.

I tested the button on emu, play and pause works even when the playback panels are hidden and without triggering the `btnPause` class. I also tested the `btnPlay` class on itemdetails page, it works too.

Now I'm figuring out how to get the focused item on the main page to be played immediately with the remote `MediaPlayPause` button (without going into the itemdetails page).

I'll test later on my TV and clean up the codes then fork this.

**Comment by dmitrylyzo** [comment]
If you register `MediaPlayPause` key, `fastforward`/`rewind` and `nextTrack`/`previousTrack` commands will stop working for Smart Remote because button hint won't be displayed. That why I don't turned it on.
Basic Remote doesn't have such "magic" button - just separate `Play`, `Pause`, etc.

> I tested the button on emu, play and pause works even when the playback panels are hidden and without triggering the `btnPause` class. I also tested the `btnPlay` class on itemdetails page, it works too.

Keys works through `inputManager` commands, and you can control music played in background.

**Comment by Nazar78** [comment]
Ouh ok noted, scrape my `MediaPlayPause` intention, forgot that without the hint the other keys won't work :/

I could probably make the Info and colored A/B/C/D keys works statically but to make it dynamically customizable, I assumed by the guidelines any of these cannot be injected directly only from jellyfin-tizen itself but through jellyfin-web prior? If so I need to first fully understand the jellyfin-web which I can't find any relevant docs yet.

**Comment by dmitrylyzo** [comment]
Some more info https://github.com/jellyfin/jellyfin-web/issues/303

**About menu**
I think that in order for menu to be displayed using some kind of command, need to make it navigable at first. Feature was mentioned here https://github.com/jellyfin/jellyfin-web/issues/608
Some time ago I started implementing menu navigation (pretty simple actually), but put it off - don't like how `focusManager` handles containers.

> Ouh ok noted, scrape my MediaPlayPause intention, forgot that without the hint the other keys won't work :/

If someone wants only Play/Pause (without hint), I believe it could be controlled with `registerKey`/`unregisterKey` (need to add such feature to `NativeShell`) depending of user settings and/or current view/page. Personally, I prefer to have extra commands from hint.

> I could probably make the Info and colored A/B/C/D keys works statically but to make it dynamically customizable, I assumed by the guidelines any of these cannot be injected directly only from jellyfin-tizen itself but through jellyfin-web prior?

Keys are handled in `jellyfin-web` by views itself (for example, `controllers/playback/videoosd.js`) or globally (if no one else catches it) in `components/input/keyboardnavigation.js`.

I didn't discuss this with others, but I think that we need an extra page in `Settings` for control customization, like in games: shortcuts/hotkeys for different perspectives (site in general, videoplayer), deadzones for gamepads, disabling gamepads completely, etc.

**Comment by bebbenhorst** [comment]
@dmitrylyzo question I got jellyfin running but I can't click on the dropdown menu's 
for example if I click on an movie and want to select another subtitle.
Also I don't get the hints when I play something and the subtitles are not showing.

Is this something in the config.xml that I have to change?

I tried the normal samsung remote with all the buttons seperated.

**Comment by dmitrylyzo** [comment]
@bebbenhorst could you open a new issue (or even 2: dropdown and subtitles) and mark it with "[Tizen 2.3]"? This one is more about additional key support. Moreover, most of issues are related to `jellyfin-web`, and I can move it there in this case.
Also, please specify in new issue (about subtitles) what subtitles: SRT/ASS, external/embedded.
