### ISSUE TITLE
Missing fanart on tv

### ISSUE THREAD

**Issue by RomainCZX** [jellyfin/jellyfin-tizen#111]
Hello,

I installed the application on my Samsung Tizen TV, everything works perfectly, except that I don't have the fanart (the movie logo). The logo is present on the web interface.

How to have the logo on the tv?

![image](https://user-images.githubusercontent.com/97809544/159650567-dd651c9b-1b39-49f2-bc9e-3972723e0de4.png)

**Comment by dmitrylyzo** [comment]
Logo is hidden on TV:
https://github.com/jellyfin/jellyfin-web/blob/d8e687eeca07fdb9f910dd02e0562342cbfceadb/src/controllers/itemDetails/index.js#L578-L582

That's probably because the TV layout has a larger font and a different button layout, so there is no space for the logo.

**Comment by RomainCZX** [comment]
Thank you very much, I modified the code to make the logo appear on my TV
