### ISSUE TITLE
Reverse proxy playback fail on certain video

### ISSUE THREAD

**Issue by Nazar78** [jellyfin/jellyfin-tizen#113]
Hi,

I wanted to reported this for quite some time already but I don't have the time to troubleshoot. So most of the time I'll just either watch my media over TV's DLNA or if unsupported or subtitle messed up, I'll switch over to Ubuntu's VLC running on my NAS to the TV.

I've been getting issues with playback failures recently. Clicking on play will only show the wallpaper with loading circle animation. This affects most of the newly acquired media.

I'm not sure where's the fault because it plays correctly both on the web browsers and Android app. It also plays correctly on the TV's DLNA built-in app. When I tried to debug in chrome, I see a blank screen which I'm sure I've tried debugging in the past and I can see the screencast, not sure what changes in chrome would've prevented this.

When I clicked play on the TV remote, I only get wallpaper with the loading circle animation from the TV. Debug chrome screen is blank but as soon as I clicked play on the TV remote, the debug console shows the error as screenshot attached. There's nothing particular in the Jellyfin's server log.

Would appreciate if anyone could point out the issue as it has been flawless in the past.

![Screenshot 2022-03-24 234406](https://user-images.githubusercontent.com/2883688/159955889-e713863b-364d-4a3f-a79f-f529e5815385.png)

Jellyfin: 10.7.7 debian
TV: Samsung RU8000 Tizen 5.0 latest firmware
Media:
> Video
Title1080p H264 SDR
CodecH264
AVCNo
ProfileHigh
Level40
Resolution1918x1038
Aspect ratio1.85:1
InterlacedNo
Framerate23.976025
Bitrate10654 kbps
Bit depth8 bit
Video rangeSDR
Color spacebt709
Color transferbt709
Color primariesbt709
Pixel formatyuv420p
Ref frames1
NAL0

> Audio
TitleEn - Dolby Digital - 5.1 - Default
Languageeng
CodecAC3
Layout5.1
Channels6 ch
Bitrate384 kbps
Sample rate48000 Hz
DefaultYes

> Subtitle
TitleEn - Default
Languageeng
CodecSUBRIP
DefaultYes
ForcedNo
ExternalNo

> Subtitle
TitleEn
Languageeng
CodecSRT
DefaultNo
ForcedNo
ExternalYes

Edited: I just tried doing a fresh pull of both JellyfinWeb and Jellyfin-Tizen, compiled and loaded to the TV, still same issue.

**Comment by dmitrylyzo** [comment]
The `isUdPanelSupported` error is irrelevant: it is already caught, so it cannot block the loading.
_It will be resolved by the upcoming "screen" PR._

There was a problem with the empty Chrome DevTools - Chrome 80 was required.

`SUBRIP`? :thinking: 
Someone on Matrix claimed that there is a problem with the subrip videos. But I dunno how subtitles can block loading.

**Comment by Nazar78** [comment]
> There was a problem with the empty Chrome DevTools - Chrome 80 was required.

Thanks for the hint!

> `SUBRIP`? 🤔
> Someone on Matrix claimed that there is a problem with the subrip videos. But I dunno how subtitles can block loading.

I've tried remuxing using ffmpeg to remove the subtitle but it's still the same loading circles while trying to play the video. I suspect it's the DD5.1 audio but shouldn't the audio gets transcoded like it does in the browser? Any tips would help me during debugging later.
![image](https://user-images.githubusercontent.com/2883688/160130612-0dac057b-ce6f-4320-9fb4-74961ddc2e2a.png)

**Comment by dmitrylyzo** [comment]
I currently have no problem with transcoding of video (2+ hours) when not burning embedded subtitles.
But when burning embedded subtitles, the player requests the first segment (`0.ts`), but doesn't receive it. _Looked via wireshark._
The server seemed to send the response but slow: 44s. _Timeout? :thinking: But there is no network error._
Reproducible in the Tizen 5.0 emulator.

**Comment by Nazar78** [comment]
I found the reason, it does play normally, even with Subrip, if I connect with LAN IP but not with reverse proxy. This only happens in Tizen. No issue with other platforms. It used to work flawlessly not sure what happened as I have not touched my reverse proxy for a long time. One of the reason I use reverse proxy is to cache the images.

I've produced the chrome debug logs between the two connection methods. Both already signed into the respective IP or Domain connection method when I launch the debugger.  However I wasn't able to see where the reverse proxy failed to play? It just stops there. The Jellyfin server and Nginx logs also doesn't show any hints.

Any other tips or advice that could help? Attached are both connecting methods logs:
> [LAN IP - 739e56f8-1939-4970-8220-b444b4db22ef.log](https://github.com/jellyfin/jellyfin-tizen/files/8353727/LAN.IP.-.739e56f8-1939-4970-8220-b444b4db22ef.log)

> [Reverse Proxy - 0365371d-1fb2-4294-8eb8-9b42835b58e8.log](https://github.com/jellyfin/jellyfin-tizen/files/8353728/Reverse.Proxy.-.0365371d-1fb2-4294-8eb8-9b42835b58e8.log)

**Comment by dmitrylyzo** [comment]
@Nazar78 Could you look this line in the log?
```
[23:52:24] [WRN] [45] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://IP/videos/bd8ea027-57ca-ec8e-fd45-e3292b404768/hls1/main/0.ts?DeviceId=... to IP in 0:00:44.4259046 with Status Code 200
```
This is the request of the first segment, and it is rejected (not received) by Tizen.

I didn't use any proxy when testing.

I also roughly implemented AVPlay player and it just cancels the request after 30s. So I guess anything more than that will break the playback (at least at the start).

I think we need to send the first segment ASAP, but this is a server-side job.

**Comment by Nazar78** [comment]
> @Nazar78 Could you look this line in the server log?

That line ".../main/0.ts?DeviceId=..." doesn't exists in the server log when I play this particular video through the reverse proxy.

BTW I looked back at my proxy, I remembered I did put a tweak (https://github.com/jellyfin/jellyfin-tizen/issues/46#issuecomment-705147325) in the response for "/System/Info/Public" to force clients to connect to the reverse proxy domain instead of the local IP. It has been working till recently.

> {"LocalAddress":"https://my-reverse-proxy-domain.com/","ServerName":"Nimbustor4","Version":"10.7.7","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"177c47a1286f4b5888acf9518aefcd61"}

When I removed this tweak, the video does play back but it's requested over local IP instead of the reverse proxy:
> [2022-03-26 08:03:08.050 +08:00] [WRN] [26] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://[****:d803:db4b:250c:****:48ff:fe8d:****]:8096/....

@dmitrylyzo Can I ask why the tweak works on browsers and apps but not in Tizen? Also besides using this tweak, is there any other way we force the connection to go through the reverse proxy instead of falling back to local IP? It's IPv6 in my case as seen in the logs. Actually I don't understand why requests over a domain should fallback to local IP? I have memory caching setup in Nginx for the images so all clients will be served from the cache instead of disk. Thank you for looking into this.

**Comment by dmitrylyzo** [comment]
> That line ".../main/0.ts?DeviceId=..." doesn't exists in the server log when I play this particular video through the reverse proxy.

OK then. The server is probably quick enough.

> Also besides using this tweak, is there any other way we force the connection to go through the reverse proxy instead of falling back to local IP?

Try the `published-server-url` option (at least 10.8 has it).
```sh
jellyfin --help
...
  --published-server-url    Jellyfin Server URL to publish via auto discover process
```
If the server is on Linux, you can add this option in `/etc/default/jellyfin`.

**Comment by Nazar78** [comment]
Thank you @dmitrylyzo for the suggestion.

Seems `published-server-url` changes the same parameter as the tweak that I had, which is to supply `"LocalAddress":"https://my-reverse-proxy-domain.com/",...` to the `/System/Info/Public` request. This leads back to the same issue. I noticed the followings:

1. If `published-server-url` is set to the reverse proxy domain, on startup Jellyfin-Tizen will connect to this URL. The navigations works I can see request being made in the proxy logs but playing video will result in loading circles.
 
2. If `published-server-url` is not set, on startup Jellyfin-Tizen will only request these two URIs below as seen in the proxy log then continue to use the local IP in the parameter set in `/system/info/public`. There's no further connection requests to the reverse proxy, all switched to the local IP. I don't understand this behavior.
> 2400:d803:db4b:250c:*:*:*:* - BYPASS [27/Mar/2022:03:10:22 +0800] "GET /Branding/Css HTTP/2.0" 200 20 "-" "Mozilla/5.0 (SMART-TV; LINUX; Tizen 5.0)
> 2400:d803:db4b:250c:*:*:*:* - BYPASS [27/Mar/2022:03:10:22 +0800] "GET /system/info/public HTTP/2.0" 200 20 "-" "Mozilla/5.0 (SMART-TV; LINUX; Tizen 5.0)

As I mentioned earlier, this only happens in Jellyfin-Tizen, not the Jellyfin-Web or phone apps. Why this behavior though?

The expected result is Jellyfin-Tizen should connect and use the given URI, a HTTPS domain in this case, not fallback to the `LocalAddress`. What is actually the function of `published-server-url` a.k.a. `LocalAddress`, is it related to Chromecast or DLNA (which both I'm not using)?

**Comment by dmitrylyzo** [comment]
Now you can omit one proxy option :smile: 

> 1\. If `published-server-url` is set to the reverse proxy domain, on startup Jellyfin-Tizen will connect to this URL. The navigations works I can see request being made in the proxy logs but playing video will result in loading circles.

Even no requesting the `videos` endpoint?
iirc, you had filtered this endpoint from caching, right?
btw, `PlaybackInfo` endpoint shouldn't be cached as well. It describes how the item will be played.

> 2\. If `published-server-url` is not set, on startup Jellyfin-Tizen will only request these two URIs below as seen in the proxy log then continue to use the local IP in the parameter set in `/system/info/public`. There's no further connection requests to the reverse proxy, all switched to the local IP. I don't understand this behavior.
>
> As I mentioned earlier, this only happens in Jellyfin-Tizen, not the Jellyfin-Web or phone apps. Why this behavior though?

Tizen app is the only one (last) that uses `jellyfin-web`'s server selecting. In this case "reconnecting" is used:
https://github.com/jellyfin/jellyfin-apiclient-javascript/blob/18ba56472415fb08a7517f9e364f994537c163d5/src/apiClient.js#L3891-L3902
- `ManualAddress` is what you have entered
- `LocalAddress` is LAN address
- `RemoteAddress` is Internet (?) address

It tries to connect to all 3 with different timeouts (that's probably why you see the proxy being requested), and whoever responses first will be the working address.

The other (phone) apps are webviews and open the remote page as a browser. In this case it locks to the manual address: https://github.com/jellyfin/jellyfin-web/blob/2d52da24070eed363684c2b6af91ef8d48abbaf4/src/components/ServerConnections.js#L32

> The expected result is Jellyfin-Tizen should connect and use the given URI, a HTTPS domain in this case, not fallback to the `LocalAddress`.

I probably agree with you: the user expects the app to connect via the entered address.
At the same time, that was probably done to avoid connecting by remote address to the local server (from Emby, I guess). But I am not sure.

> What is actually the function of `published-server-url` a.k.a. `LocalAddress`, is it related to Chromecast or DLNA (which both I'm not using)?

Probably. There is also auto discover in webOS and phone apps. _I need to implement this in Tizen._

Looks like it can be the environment variable `JELLYFIN_PublishedServerUrl`:
https://jellyfin.org/docs/general/administration/configuration.html

**Comment by Nazar78** [comment]
> Now you can omit one proxy option 😄

That's one less worry 🤣

> Even no requesting the `videos` endpoint?

No I don't see any request for the videos. Probably something happened in the frontend request but I wasn't able to find it in the chrome debug logs either. It's like eventually nothing was requested to either proxy nor local IP when the play button gets pressed.

> iirc, you had filtered this endpoint from caching, right?
> btw, `PlaybackInfo` endpoint shouldn't be cached as well. It describes how the item will be played.

Yes it's filtered from caching, but it should still go through the proxy right? Only images gets cached `.+/Images/.+`, all the other requests will get bypassed directed to the backend.

I tried something today, which is to Wifi tether my TV to my phone's mobile data. The `published-server-url` or the `LocalAddress` "tweak" is not set, I already removed since it's problematic. Same thing happened. I was able to connect and navigate but unable to play. So this issue is actually more serious than I thought, meaning another Tizen client outside my network won't be able to play.

Would you be able to test Jellyfin-Tizen with your local reverse proxy? This is where both Jellyfin-Server and the reverse proxy is on the same local subnet. I think without setting up a reverse proxy (any proxy as stated in https://jellyfin.org/docs/general/networking/index.html), I don't think you would be able to see this strange behavior I'm trying to point out. It just needs any free DDNS domain and SSL cert such as Let's Encrypt. And of course some port forwarding.

Or if that's too much to ask, if you could then just try debug from my server. See if you can play the demo video on your Tizen client. Do note that I can play the video since I've removed the `published-server-url` and the `LocalAddress` in `/system/info/public` defaults to my LAN IP. When my TV is connected to local network, I can play the video, but if my TV is using my mobile data, the video won't play using the details below:
![image](https://user-images.githubusercontent.com/2883688/160262583-f68faa1d-b209-4d2a-9013-81e25f292211.png)

**Comment by dmitrylyzo** [comment]
I tried yours on Tizen 5 emulator - the same `Circle of Death`. Looking at the `src` attribute of the `video` element, it is going to play `Direct` (`HOST/Videos/.../stream.mkv?Static=true&mediaSourceId=...&deviceId=...&api_key=...&Tag=...`).
If I limit `Internet quality` with `1080p - 10M` (and lower), it plays (obviously transcoded) via HLS endpoint (`master.m3u8`).
Browser works as you said (`DirectStreaming`), but it also uses HLS endpoint.
Using `curl` on that URL produces an error: `(92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)`
So something wrong with direct play endpoint, imo.

We have demo server on `https://demo.jellyfin.org/stable`.
I can play `Direct` from it: `Pioneer One` and `Caminandes: Llama Drama`.
And can "curl" its direct endpoint.

**Comment by Nazar78** [comment]
> So something wrong with direct play endpoint, imo.

This is where we need your expertise. I'm at lost 😭

> We have demo server on `https://demo.jellyfin.org/stable`.
> I can play `Direct` from it: `Pioneer One` and `Caminandes: Llama Drama`.
> And I can "curl" its direct endpoint.

The difference is I believe the demo server is using direct HTTPS setup but I'm using reverse proxy. I've masked my nginx config not to show the proxy server name but you can tell the differences at the screenshot below:
![Screenshot_20220327-164307_ConnectBot](https://user-images.githubusercontent.com/2883688/160273917-6602e097-bb1e-494c-a684-7b9a3076801b.png)

**Comment by Nazar78** [comment]
@dmitrylyzo 

> (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

I'm leaning towards this error that you got, will try to see what I can find.

By any chance the curl endpoint that failed contains `Content-Length: 97` header request? I'm seeing lots of these in the Jellyfin Server log since you started debugging like 2 hours ago.

> [2022-03-27 15:10:32.778 +08:00] [ERR] [31] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HMGFBAR0KOH7"", Request id ""0HMGFBAR0KOH7:00000015"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (25 of 97).
[2022-03-27 15:10:34.151 +08:00] [ERR] [18] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HMGFBAR0KOH6"", Request id ""0HMGFBAR0KOH6:00000004"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (25 of 97).
[2022-03-27 15:10:35.520 +08:00] [ERR] [18] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HMGFBAR0KOH8"", Request id ""0HMGFBAR0KOH8:00000002"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (25 of 97).

**Comment by dmitrylyzo** [comment]
Is this video symlinked?

**Comment by Nazar78** [comment]
> Is this video symlinked?

Yes but either way symlinked or not it still produces the same error. Anyway I've added a physical copy of the video named demo2.mkv.

**Comment by Nazar78** [comment]
@dmitrylyzo 
The same request failed whilst endpoint made via reverse proxy but successful via local IP.

![image](https://user-images.githubusercontent.com/2883688/160276598-09efb663-fcd2-4695-bdf6-583b8b0bcd15.png)

In the jellyfin log:
> ==> jellyfin/log_20220327.log <==
[2022-03-27 18:02:04.483 +08:00] [ERR] [89] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HMGFBAR0KP24"", Request id ""0HMGFBAR0KP24:00000002"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (25 of 97).

In the nginx log (the timestamp differs as I've set a higher log buffer delayed, but this is the error from the similar request):
> 2022/03/27 17:24:10 [error] 17816#17816: *5062 upstream prematurely closed connection while reading upstream

I also saw inconsistent HTTP/1.1 and HTTP/2.0 requests in the nginx log for the similar endpoint which I suspect a connection upgrade is being requested but somehow it breaks somewhere.

**Comment by dmitrylyzo** [comment]
> The same request failed whilst endpoint made via reverse proxy but successful via local IP.

Maybe it is cached after all (the endpoint `/Videos/{itemId}/stream.{extension}`)?

> upstream prematurely closed connection while reading upstream

This is probably me cancelled the downloading via direct endpoint.

>  also saw inconsistent HTTP/1.1 and HTTP/2.0 requests in the nginx log for the similar endpoint which I suspect a connection upgrade is being requested but somehow it breaks somewhere.

I tested HTTP 1/2

`curl` works with the non-symlinked. I even can download it. And `XmlHttpRequest` in app also works.
This fact destroys the "caching" assumption (above). Or maybe the request headers are involved?

`video` element still doesn't. Even AVPlay doesn't get a response and cancels the request after 30s, then it tries the transcoding.

**Comment by Nazar78** [comment]
> > The same request failed whilst endpoint made via reverse proxy but successful via local IP.
> 
> Maybe it is cached after all (the endpoint `/Videos/{itemId}/stream.{extension}`)?

No the Videos path is not cached but think there's some config issues at my end. 

Think it's fixed... Turns out when I commented out the cache it works with the combination of `--published-server-url=https://my-reverse-proxy-domain`. But as I mentioned earlier I haven't touched any of my settings for a long time.  It's just recently some videos won't play due to this error. Might be some of the endpoints leaked into the caching which I'm not aware of that caused this issue. 

So now I moved the `proxy_cache proxy;` parameter into the location context block and it worked! Previously I placed the `proxy_cache proxy;` outside the location context block so that I don't have repeat the `proxy_*` parameters for all the locations that needs caching and just use `set $nocache 1;` arguments for those that should be filtered  off.

```
location ~* .*/(Images|web)/.+ {
		proxy_cache proxy; #################### This cannot be placed outside of the location block!
		proxy_cache_valid 200 301 302 7d;
		proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
		proxy_cache_bypass $nocache;
		proxy_no_cache $nocache;
		proxy_cache_revalidate on;
		proxy_cache_min_uses 1;
		proxy_cache_background_update on;
		proxy_cache_lock on;
		proxy_cache_purge $purge_method;
		proxy_pass http://jellyfin;
	}
```

Thank you again for the great help! Your testings, insights and hint (`(92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)`) gave me a clue. Also the `--published-server-url` which I'm not aware of is also really helpful so Jellyfin-Tizen is forced to connect via the reverse proxy domain instead of local IP.

I'll close this for now but I'll leave the demo server for few days incase you want to test.

**Comment by dmitrylyzo** [comment]
Yes, now non-symlinked works fine. Symlinked will work in 10.8 (just tested unstable).

> Might be some of the endpoints leaked into the caching which I'm not aware of that caused this issue.

I also thought, can it be because of the MIME type (`text/plain`)?

Anyway, I am glad you solved the problem.

**Comment by Nazar78** [comment]
> I also thought

Great thoughts!!!

> can it be because of the MIME type (`text/plain`)?

Previously I override the MIME to rewrite the `LocalAddress` "tweak" but it doesn't seems to be the issue since I already removed in turn now using the `--published-server-url`.

`proxy_cache proxy; #################### This cannot be placed outside of the location block!`

This was the culprit! Even though nginx manual says `Context:	http, server, location`. It seems to affect the rest of the location blocks when placed outside i.e. in http or server. Many thanks again @dmitrylyzo !!!
