### ISSUE TITLE
(Feature request) Possibility to choose color of the subtitles

### ISSUE THREAD

**Issue by garret** [jellyfin/jellyfin-tizen#118]
I just managed to install Jellyfin on my Samsung TV and I have been positively surprised how well reactive the application seems to be. For me to be perfect and completely substitute Plex I would like to have the possibility to also choose the color of the subtitles (really like to have them in light yellow). 

May I kindly ask if it is something that you think it will be introduced at some point? 
Thank you very much in the meanwhile for the hard work and fantastic job!

**Comment by dmitrylyzo** [comment]
In fact, the color is customizable, but the field is hidden. There is a PR (https://github.com/jellyfin/jellyfin-web/pull/3549) that unhides it, but like I said, color picker would be better.
In any case, this can only be done in web.

**Comment by garret** [comment]
Thank you, I managed to get the subtitles color thanks to that PR. I will close this issue and hopefully that PR will get accepted.
