### ISSUE TITLE
Are all 31.1 MiB of fonts actually needed?

### ISSUE THREAD

**Issue by HimbeersaftLP** [jellyfin/jellyfin-tizen#12]
These fonts make the application huge compared to almost every other Tizen App in the store (they usually have a few MBs while the wgt file for Jellyfin-Tizen measures 36.8MiB).
Considering the very limited amount of space on most user's Samsung Smart TVs (as seen in other issues on this repo and the Samsung developer forums), it might be a better idea to use a system font, even if that makes the font inconsistent with other platforms.

**Comment by dmitrylyzo** [comment]
If I understand correctly these fonts are parts of a big one. They are divided mainly to speedup loading over network because no need to load whole range. Probably they could be smaller being merged.

Android app has also become bulky. So this definitely should be fixed.

**Comment by ferferga** [comment]
@HimbeersaftLP jellyfin/jellyfin#2871 and jellyfin/jellyfin-web#1087 will fix this problem

**Comment by dkanada** [comment]
resolved with jellyfin/jellyfin-web#2010
