### ISSUE TITLE
App icon in the tray is widen/distorted on 2016+ TVs

### ISSUE THREAD

**Issue by DarkFighterLuke** [jellyfin/jellyfin-tizen#121]
In the tray at the bottom of the screen, where you can launch apps added to the home page (I don't know if it has/what is the particular name), the Jellyfin icon is weird and distorted, because the square logo is take instead of this two:
- https://github.com/jellyfin/jellyfin-ux/blob/master/branding/tizen/logo_fg.png
- https://github.com/jellyfin/jellyfin-ux/blob/master/branding/tizen/logo_bg.png

According to Tizen Docs, this kind of app logo is available for 2016 or newer TVs, which is in fact my case.

**Comment by dmitrylyzo** [comment]
There is no such property in `config.xml`.
As far as I know, they are added when publishing.

**Comment by DarkFighterLuke** [comment]
Oh ok, thank you.
