### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by iaimans** [jellyfin/jellyfin-tizen#127]
Hello,

I've just build and installed the latest version of Jellyfin on my TV and every time I try to play a video, the spinner appears and keeps spinning without playing the video. I've checked the server's logs but nothing strange is showing up.

Thanks

**Comment by paulieo001** [comment]
I'm currently having the same issue. Transcoding is enabled for the profile. 

Nothing in the server logs apart from:
[2022-07-15 21:58:51.295 +01:00] [INF] [48] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.0.174" request

No other info.

**Comment by Jokus0806** [comment]
I'm also having this issue. I've installed the latest version on my Tizen 3.0 TV. Also nothin in my Server logs apart from:

[2022-07-23 13:49:54.537 +02:00] [INF] [44] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.8.188" request
[2022-07-23 13:49:57.680 +02:00] [INF] [44] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.8.188" closed

**Comment by gogo199432** [comment]
Can confirm, getting the same issues as above. Just built the app yesterday. Browsing works fine, but no matter what media I try to play, only the spinner appears and hangs indefinitely. No transcoding or any other relevant log appears, except for the websocket lines that others mentioned.

**Comment by sushil012** [comment]
Today according to your instructions I have also built the jellyfin-tizen app several times. Every time it installs very well, shows everything from my server, even the video thumbnails but if I want to play something, a blue spinner appears and keeps spinning. Please I want a urgent solution if it is possible. My tv is samsung NU7470.
