### ISSUE TITLE
Help with MacOS: No right click on Device Manager to Permit Install apps

### ISSUE THREAD

**Issue by PauFCB** [jellyfin/jellyfin-tizen#135]
Hi, I don't have the option to right click on my connected device and when I try to install it I see this error:

install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt
was_install_app return WAS_TRUE
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[7]
app_id[AprZAARz4r.Jellyfin] installing[10]
app_id[AprZAARz4r.Jellyfin] installing[13]
app_id[AprZAARz4r.Jellyfin] installing[15]
app_id[AprZAARz4r.Jellyfin] installing[18]
app_id[AprZAARz4r.Jellyfin] installing[21]
app_id[AprZAARz4r.Jellyfin] installing[23]
app_id[AprZAARz4r.Jellyfin] install failed[118012]
spend time for wascmd is [4353]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:10.652

Please, what can I do? thanks

**Comment by dmitrylyzo** [comment]
After applying `Permit install application` it should just say "success", iirc. You probably need to reboot the TV after that (_I don't remember_) - long press power button on the remote.

**Comment by PauFCB** [comment]
Hi, thanks for the quick response. The problem that I have is that I can't see the menu Permit install application. The right click don't do aniything.

**Comment by PauFCB** [comment]
> After applying `Permit install application` it should just say "success", iirc. You probably need to reboot the TV after that (_I don't remember_) - long press power button on the remote.

I see this person have similar issue and solve it: https://github.com/jellyfin/jellyfin-tizen/issues/32 but didn't know how

**Comment by dmitrylyzo** [comment]
> I see this person have similar issue and solve it: #32 but didn't know how

They have Tizen 2.3 which for some reason requires mixed (not Samsung) certificate.
What model is your TV?

> The problem that I have is that I can't see the menu Permit install application. The right click don't do aniything.

Do you see TVs filesystem in the Device Manager?
[Here](https://docs.tizen.org/application/tizen-studio/common-tools/device-manager/), that menu entry is shown when clicking the File Explorer. _Sorry I can't check this for you right now._

I haven't tried Tizen certificate on my TV (Tizen 4) till Tizen Studio 3, but [someone](https://github.com/jellyfin/jellyfin-tizen/issues/92#issuecomment-1187626256) mentioned that custom build can be installed. So maybe Tizen (not Samsung) certificate can be used now.

**Comment by PauFCB** [comment]
> > I see this person have similar issue and solve it: #32 but didn't know how
> 
> They have Tizen 2.3 which for some reason requires mixed (not Samsung) certificate. What model is your TV?
> 
> > The problem that I have is that I can't see the menu Permit install application. The right click don't do aniything.
> 
> Do you see TVs filesystem in the Device Manager? [Here](https://docs.tizen.org/application/tizen-studio/common-tools/device-manager/), that menu entry is shown when clicking the File Explorer. _Sorry I can't check this for you right now._
> 
> I haven't tried Tizen certificate on my TV (Tizen 4) till Tizen Studio 3, but [someone](https://github.com/jellyfin/jellyfin-tizen/issues/92#issuecomment-1187626256) mentioned that custom build can be installed. So maybe Tizen (not Samsung) certificate can be used now.

My Samsung is a QLed: QE65Q6FNA
In device manager I see: TV 4.0 and my decive synced and connected, but don’t know how to find that menu File Explorer to appear. Thanks

**Comment by PauFCB** [comment]
EDIT: Solved installing they CLI
