### ISSUE TITLE
Samsung UN55K6500 Failed to install application

### ISSUE THREAD

**Issue by MrGmaw** [jellyfin/jellyfin-tizen#138]
usuario@mawflix:~/jellyfin-tizen$ ../tizen-studio/tools/ide/bin/tizen install -n Jellyfin.wgt -t UN55K6500
Transferring the package...
Transferred the package: /home/usuario/jellyfin-tizen/Jellyfin.wgt -> /opt/usr/apps/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /opt/usr/apps/tmp/Jellyfin.wgt
was_install_app return WAS_TRUE
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] install failed[118]
spend time for wascmd is [10928]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:50.236

**Comment by dmitrylyzo** [comment]
Is this Tizen 2.x?
If so, a mixed certificate might help https://github.com/jellyfin/jellyfin-tizen/issues/19#issuecomment-629816880

**Comment by MrGmaw** [comment]
Thank you dmitrylyzo for your help.
I enabled Install Apps with a right click on my SmartTv Id in Tizen Device Manager, and that was it. Now the jellyfin.wgt app was installed with any problem.

**Comment by MrGmaw** [comment]
solved enabling Permit to install applications (Right click on TV Id in Device Manager)
