### ISSUE TITLE
Remove requirement of Samsung account in README

### ISSUE THREAD

**Issue by Darth4212** [jellyfin/jellyfin-tizen#139]
A Samsung account is no longer needed in order to create certificates or even complete the process.

**Comment by saxicek** [comment]
I can confirm this. I did not register for Samsung account and did not install Certificate Manager from "Getting Started" points 2-4. Still I was able to upload the package to my UE43KU6072.

**Comment by dmitrylyzo** [comment]
> Still I was able to upload the package to my UE43KU6072.

Tizen 2.4 :+1: 

I can't tell which version of Tizen Studio it started working with. At least with Tizen Studio 4.6 my Tizen 4 accepted the app without Samsung certificate. _It didn't work in Tizen Studio 4.1._

Tizen 2.4 :heavy_check_mark: 
Tizen 4.0 :heavy_check_mark:

**Comment by Darth4212** [comment]
> I haven't tried without it - the app still requires signing with a certificate that is accepted by the TV. _need testing_
Unable to confirm which version of Tizen that works without cert signing because I did it on my fiance's aunt's TV and haven't been on site in like a month
