### ISSUE TITLE
Latest version is stuck at boot logo

### ISSUE THREAD

**Issue by Tahvok** [jellyfin/jellyfin-tizen#144]
I have tried updating jellyfin tizen to latest version, and this resulted in the app being stuck at jellyfin boot logo.

I also have an old version of jellyfin tizen that I've built a while ago, on February 4th, which is what I've been using until now.
I have rebuilt the Feb 4th jellyfin-tizen using the latest jellyfin-web repo - and it is working as it should - given the time differences between the repositories.

So not sure what change resulted in the issue since then in jellyfin-tizen.

From what I understand the tv is running tizen version 3.0
![image](https://user-images.githubusercontent.com/6513056/196006755-386fa49d-508e-4337-b410-12764ef3260f.png)

Not sure how to debug this. Please tell me what more info you need.

**Comment by dmitrylyzo** [comment]
> Not sure how to debug this.

For Linux: https://github.com/jellyfin/jellyfin-tizen/issues/79#issuecomment-822068324
For Windows: https://github.com/jellyfin/jellyfin-tizen/issues/46#issuecomment-683747890

You are the second person who has encountered this problem.
I just tried [f0b29fa9cc4e168e499e292176e66073cb38596f](https://github.com/jellyfin/jellyfin-web/commit/f0b29fa9cc4e168e499e292176e66073cb38596f) on Tizen 4 and it works. It works even on webOS 1.2

**Comment by Fallenbagel** [comment]
I faced the same issue but using the `v10.8.5` branch solved the issue for me

**Comment by FrEaK-git** [comment]
Are there any news about this? I'm having the same issue and I do not want to use a old version. 🤷

**Comment by dmitrylyzo** [comment]
> Are there any news about this? I'm having the same issue and I do not want to use a old version. shrug

Until someone posts where it crashes, I can't say why, because it works on my TV (NU7400). https://github.com/jellyfin/jellyfin-tizen/issues/144#issuecomment-1279834408

**Comment by Fallenbagel** [comment]
> Until someone posts where it crashes, I can't say why, because it works on my TV (NU7400). https://github.com/jellyfin/jellyfin-tizen/issues/144#issuecomment-1279834408

I could help collect some logs this weekend. Meanwhile I'm curious, it works for you on tizen 4(?) with the `master` branch of jellyfin-web?

**Comment by dmitrylyzo** [comment]
> I could help collect some logs this weekend. Meanwhile I'm curious, it works for you on tizen 4 with the `master` branch of jellyfin-web?

Yes, it worked, at least the mentioned commit.

I am using `no-cache` on my test server (_probably doesn't matter, since the app uses the bundled jf-web_) and I access it via IP (so no certs). But I also tested the app on Jellyfin demo server and it worked.

For the record. When I was checking to see if I could use the Tizen certificate, I had to uninstall the app first.

**Comment by Afmarhome** [comment]
Hi guys 
I am new to this. Yesterday I tried to install this application following the steps in this guide. I think everything went fine, no errors, just npm warnings on building jellifin web and tizen.
I managed to install the application on the TV, NU7475, without errors, but I got stuck on the boot logo.
I don't know if it could be the same problem as yours. I have tried the additional steps "on windows" without success:

_```
Step 2: C:\tizen-studio\tools\sdb.exe shell 0 debug "AprZAARz4r.Jellyfin" "300" (I have no clue what the 300 is for)
Step 3: & "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --no-first-run --activate-on-launch --no-default-browser-check --allow-file-access-from-files --disable-web-security --disable-translate --proxy-auto-detect --enable-blink-features=ShadowDOMV0 --enable-blink-features=CustomElementsV0 --user-data-dir=C:\tizen-studio-data\chrome-user-data --app=http://192.0.0.1:7011/inspector.html?page=1 (instead of 192.0.0.1 put your TV's IP)
```_

I do NOT know if I have interpreted it right or I have to do something else. I also don't know if there is a way to access logs to see where the failure could be.

Any suggestions.

Thanks in advance

**Comment by dmitrylyzo** [comment]
@Afmarhome I can't verify Windows, but try this:
1. Connect to your TV with the `Device Manager`. You can also use SDB.
```cmd
C:\tizen-studio\tools\sdb.exe connect {TV_IP}
```
> Replace `{TV_IP}` with your TV's IP.

2. Find your TV's name. Something like `...NU7475` in SDB or `Device Manager`.
```cmd
C:\tizen-studio\tools\sdb.exe devices
```

3. Run the app.
```cmd
C:\tizen-studio\tools\sdb.exe -s {DEVICE} shell 0 debug "AprZAARz4r.Jellyfin"
```
> Replace `{DEVICE}` with your TV's name. 
> That `300` is required for Tizen 2.x/3.0

See the output - there should be a port that has been opened for debugging.

4. Forward the port.
```cmd
C:\tizen-studio\tools\sdb.exe forward --remove tcp:{PORT}
C:\tizen-studio\tools\sdb.exe -s {DEVICE} forward tcp:{PORT} tcp:{PORT}
```
> Replace `{PORT}` with the one received with the previous command.
> Replace `{DEVICE}` with your TV's name.

5. Open Chrome.
```cmd
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --enable-pinch --no-first-run --activate-on-launch --no-default-browser-check --allow-file-access-from-files --disable-web-security --disable-translate --proxy-auto-detect --proxy-bypass-list=127.0.0.1 --enable-blink-features=ShadowDOMV0 --enable-blink-features=CustomElementsV0 --user-data-dir=C:\tizen-studio-data\chrome-user-data --app="http://{TV_IP}:{PORT}"
```
> Replace `{PORT}` with the same as in the previous command.
> Replace `{TV_IP}` with your TV's IP.

If you see a blank page, try the same above with Chrome 79.

**Comment by Nazar78** [comment]
Same issue here, Tizen 5, RU8000. Debugging I got only below, seems to be pointing to "www/node_modules.@remix-run/router/dist.undefined.bundle.js". Perhaps @dmitrylyzo knows better.

![image](https://user-images.githubusercontent.com/2883688/197641192-7b26afe8-884e-4272-a53a-4311cd682e86.png)

**Comment by dmitrylyzo** [comment]
Is there any chance that this only affects Windows users? 🤔
https://github.com/jellyfin/jellyfin-web/blob/9e76319a4ccf1e58b97044d43eaa146e605d6cac/webpack.common.js#L112
Replace `split('/')` with `split(/[\\/]/)`

**Comment by Nazar78** [comment]
> Is there any chance that this only affects Windows users? 🤔 https://github.com/jellyfin/jellyfin-web/blob/9e76319a4ccf1e58b97044d43eaa146e605d6cac/webpack.common.js#L112 Replace `split('/')` with `split(/[\\/]/)`

Yes that's seems to fix it! Again great find @dmitrylyzo!

**Comment by jfshaddad** [comment]
> Is there any chance that this only affects Windows users? 🤔 https://github.com/jellyfin/jellyfin-web/blob/9e76319a4ccf1e58b97044d43eaa146e605d6cac/webpack.common.js#L112 Replace `split('/')` with `split(/[\\/]/)`

I'm also on windows and this fixed it for me too. Thank you @dmitrylyzo!

**Comment by Afmarhome** [comment]
> Is there any chance that this only affects Windows users? 🤔 https://github.com/jellyfin/jellyfin-web/blob/9e76319a4ccf1e58b97044d43eaa146e605d6cac/webpack.common.js#L112 Replace `split('/')` with `split(/[\\/]/)`

It also solve my problem, App built in windows and NU7475 device model. Thank you @dmitrylyzo!
