### ISSUE TITLE
jellyfin stuck on loading screen when opening the app.

### ISSUE THREAD

**Issue by NOOBNOOBOX** [jellyfin/jellyfin-tizen#147]
stuck on  logo that appears after opening the app, wont go past that just installed the latest version of jellyfin on tizen version 5.5. what can I do?

**Comment by dmitrylyzo** [comment]
dup #144

> what can I do?

I can't reproduce this issue on my Tizen 4 TV and emulators. You can try to debug:
https://github.com/jellyfin/jellyfin-tizen/issues/144#issuecomment-1279834408
https://github.com/jellyfin/jellyfin-tizen/issues/144#issuecomment-1289350540

Or you can just build the app with jellyfin-web `release-10.8.z` branch.

**Comment by HEPOSHEIKKI** [comment]
I had this same issue about a week ago and had to reinstall the whole JF app. Jellyfin got stuck displaying a loading spinner and not even a reboot could get it to go away.
