### ISSUE TITLE
audio or subtitle select its going to main screen

### ISSUE THREAD

**Issue by satstarter** [jellyfin/jellyfin-tizen#149]
have the app compiled and running on samsung tizen 2019
but when i try to select audio or subtitle button jellyfin closes and go to main screen

**Comment by dmitrylyzo** [comment]
Yes, it was broken by jellyfin/jellyfin-web#4095

For now, you can take jf-web before that PR was merged (jellyfin/jellyfin-web@af24337ba702e63d3a6ab27566fc6376961c7241).

**Comment by satstarter** [comment]
10.8.5 works thanx
