### ISSUE TITLE
Issue with Building on Windows

### ISSUE THREAD

**Issue by Simuman** [jellyfin/jellyfin-tizen#154]
Followed instructions as far as Build Jellyfin Web, as soon as I run the command "npm ci --no-audit" get multiple errors in Powershell (see below).

Have just clean installed NPM, NodeJS and Tizen on this Windows 10 system running on I7 7700K CPU 32GB RAM and GTX 1080ti for this build.  Versions of apps shown below.

NPM Ver = 9.1.1

NodeJS
x18.12.1

Tizen Studio
Version 5.0
Build Time 2022-04-18 14:12

![Screenshot 2022-11-16 233945](https://user-images.githubusercontent.com/39484751/202158814-b49af56f-36eb-42da-b5b5-82b09472e3f3.png)
[2022-11-16T10_25_59_748Z-debug-0.log](https://github.com/jellyfin/jellyfin-tizen/files/10020818/2022-11-16T10_25_59_748Z-debug-0.log)

**Comment by Simuman** [comment]
Thx for quick reply. 

Unfortunately ran into another error after running the command you advised which ran ok.  Then tried running the next part of the instructions as per Github guide and got this error.  Checked the folder and quite correctly Index.html does not exist.

![Next error 2022-11-17 025613](https://user-images.githubusercontent.com/39484751/202200303-b3cc4ac2-0c2a-4eb7-b621-aaf52f547e01.png)
[2022-11-16T13_49_38_834Z-debug-0.log](https://github.com/jellyfin/jellyfin-tizen/files/10022364/2022-11-16T13_49_38_834Z-debug-0.log)

**Comment by dmitrylyzo** [comment]
You forgot `/dist` in the `JELLYFIN_WEB_DIR`.

**Comment by dmitrylyzo** [comment]
[`tizen.bat` should be used.](https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Windows#build-wgt)
And
> All tools (yarn, node, tizen) are assumed to be added to the `PATH` environment variable.

Or use a full path.

**Comment by Simuman** [comment]
Hi dmitrylyzo,

Thanks for all the help.  Finally managed to build the file correctly, as was missing some important syntax not shown on the guide.  Very happy now that I've got it install on my TV.  Hopefully there will be a installation file for Samsung TV's soon, so many more self hosters will be able to implement this app as it's great.
