### ISSUE TITLE
Tizen Samsung

### ISSUE THREAD

**Issue by amizi** [jellyfin/jellyfin-tizen#159]
Amizi@amizi-64:~/jellyfin-tizen$ tizen build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e " yarn. lock"
tizen: Command not found.

What am I doing wrong

**Comment by dmitrylyzo** [comment]
It is located in Tizen Studio, `~/tizen-studio/tools/ide/bin/tizen`.
