### ISSUE TITLE
Really choppy scrolling in menus

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [jellyfin/jellyfin-tizen#162]
Scrolling between items in libraries and the front page is really choppy and the animation is slow, is anyone else having this issue or is it just me?

**Comment by IvanBernatovic** [comment]
@HEPOSHEIKKI I have the same issue but it's a bit better if I disable images in the background.

**Comment by kraM1tt** [comment]
It's faster than Plex for me lol

**Comment by TBE4034** [comment]
I have this same issue with no custom css or backdrop. Scrolling through movie listings is choppy and the only device with the issue is the Samsung TV. No issues on LG TV, MacBook, iPhones, etc.

**Comment by kraM1tt** [comment]
I will do when I get a chance, can you post a video of your slow scrolling?

**Comment by HEPOSHEIKKI** [comment]
> I will do when I get a chance, can you post a video of your slow scrolling?

Here is the performance on my TV: https://youtu.be/4HVnE1w0kM8
Here is the performance on an emulator: https://youtu.be/hSvaC-wYwlQ

**Comment by kraM1tt** [comment]
Ah that's really choppy, I assumed you meant the metadata/artwork loading in was causing choppy loading behaviour, I can confirm mine is the same as yours after just testing, sorry about the confusion. 

Samsung RU7100 2019

**Comment by HEPOSHEIKKI** [comment]
Any idea what could be causing this?

**Comment by alok-1019** [comment]
have someone found any solution to this ? Can we turn off animations while scrolling by using Custom CSS ? I believe animations during scrolling makes the scrolling choppy.

**Comment by alok-1019** [comment]
> > Can we turn off animations while scrolling by using Custom CSS ?
> 
> https://github.com/jellyfin/jellyfin-web/blob/d06b631171d127bddbf05bdfe4dd7ea94cd74c1e/src/components/scrollManager.js#L479-L481

should I delete those lines and build wgt file for samsung tv ?
function useSmoothScroll() {
    return !!browser.tizen;
} should i delete these lines.

**Comment by dmitrylyzo** [comment]
> should I delete those lines and build wgt file for samsung tv ?

```js
return false;
```

**Comment by alok-1019** [comment]
> > should I delete those lines and build wgt file for samsung tv ?
> 
> ```js
> return false;
> ```

Thanks for replying.
But that did not work. I changed that code and installed on TV but animations are still there when  scrolling. 
In Plex, there is an option "Reduce Motion" which turns off animations and makes Plex faster. 
Such an option in jellyfin would be great. Please add it.
But for now, could you please tell me what should I do to turn off animations by changing code ?

**Comment by dmitrylyzo** [comment]
> But for now, could you please tell me what should I do to turn off animations by changing code ?

There is no other way to control smooth scrolling other than the function mentioned.
[10.8](https://github.com/jellyfin/jellyfin-web/blob/8e37078b6066715b27fd2dde1f7d1eda216044d9/src/components/scrollManager.js#L473-L482)
[10.9](https://github.com/jellyfin/jellyfin-web/blob/7c57583adfc851013255a800b7c973ea10150c8c/src/components/scrollManager.js#L476-L481)
Returning `false` disables smooth scrolling. It is currently enabled only on Tizen.

**Comment by alok-1019** [comment]
> Returning `false` disables smooth scrolling. It is currently enabled only on Tizen.
Thanks. It worked. Now, Emby on Samsung TV is lot faster. Also, Consider adding an option in Emby App to disable smooth scrolling. Thanks.

**Comment by HEPOSHEIKKI** [comment]
> > But for now, could you please tell me what should I do to turn off animations by changing code ?
> 
> There is no other way to control smooth scrolling other than the function mentioned. [10.8](https://github.com/jellyfin/jellyfin-web/blob/8e37078b6066715b27fd2dde1f7d1eda216044d9/src/components/scrollManager.js#L473-L482) [10.9](https://github.com/jellyfin/jellyfin-web/blob/7c57583adfc851013255a800b7c973ea10150c8c/src/components/scrollManager.js#L476-L481) Returning `false` disables smooth scrolling. It is currently enabled only on Tizen.

I thought I replied to this already, weird...

Well anyway, I tried this a few weeks ago (unless I hallucinated everything, my short term memory is lacking) and it ran a lot better. If this can be made default (which it should be looking at the code??) I consider this issue ready to be closed.
