### ISSUE TITLE
Problem report container / format capabilities of tv

### ISSUE THREAD

**Issue by bsod-haunted** [jellyfin/jellyfin-tizen#163]
Hi,
here is the current setup:

- Server v10.8.8 installed in a fresh debian envoirement with the official install script.
- Tizen app on tv [precompiled from this repo](https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2022-12-05)
- a 4k Samsung TV from 2021.

There are issues with playing back 4K HDR videos encoded in h.265 that are in an MKV container. I reported this in a comment of [issue 94](https://github.com/jellyfin/jellyfin-tizen/issues/94).

As suggested in this [comment](https://github.com/jellyfin/jellyfin-tizen/issues/94#issuecomment-1364694952) in the same issue, I disabled "Allow video playback that requires transcoding".
This "solved" the problem, as in the media is now correctly playing back on my tv.
The dashboard shows the following:

<details><summary>Bevore the change / enabled transcoding</summary>
<p>
The media is being converted into a format that is compatible with the device that is playing the media.
Framerate: 12fps

28.0 Mbps TS H264 AAC

Reason for transcoding:
The container is not supported
</p>
</details>

<details><summary>after the change / disabled transcoding</summary>
<p>
The video stream is compatible with the device, but has an incompatible audio format (DTS, Dolby TrueHD, etc.) or number of audio channels. The video stream will be repackaged losslessly on the fly before being sent to the device. Only the audio stream will be transcoded.

Power consumed by direct streaming usually depends on the audio profile. Only the video stream is lossless.
</p>
</details>

<details><summary>This is the media Information</summary>
<p>

Video
Title: 4K HEVC HDR
Codec: HEVC
Profile: Main 10
Level: 153
Resolution: 3840x1600
Aspect ratio: 2.40:1
Interlaced: No
Framerate: 23.976025
Bitrate: 16426 kbps
Bit depth: 10 bit
Video range: HDR
Video range type: HDR10
Color space: bt2020nc
Color transfer: smpte2084
Color primaries: bt2020
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: Ger - DTS-HD MA - 5.1 - Default
Language: ger
Codec: DTS
Profile: DTS-HD MA
Layout: 5.1
Channels: 6 ch
Bitrate: 2260 kbps
Sample rate: 48000 Hz
Bit depth: 16 bit
Default: Yes
Forced: No
External: No

</p>
</details>

The behaviour is the same with every 4k HDR file I have.

If you need more information, i will do my best to provide it.

**Comment by SchoolGuy** [comment]
I can add to this issue my TV as well. I can't play the following formats:

- 4K HVEC HDR
- 1080p h264 SDR

Transcoding is atm not an option for my hardware as well sadly.

TV is a Samsung Q50 AAUXZG. After some investigation, it seems that my Oneplus 8 with Android 12 is also unable to play these files. This is odd because I am very sure that it should be able to handle these files. So maybe it is not a Tizen issue but a server/in a shared libray one?

**Comment by ApexArray** [comment]
Having similar issues here on my Samsung UN70NU6900FXZA

I haven't kept track of exactly what works and what doesn't, but I know that enabling subtitles for 4k MKV content seems to always encode, even if they're embedded subtitles or in a separate SRT file.

Will pay more attention to the specifics next time I'm in front of the TV.

**Comment by dmitrylyzo** [comment]
It seems that [this](https://github.com/jellyfin/jellyfin/blob/8de052646ca0a852dcad03069a1904433f909653/Jellyfin.Api/Helpers/DynamicHlsHelper.cs#L207-L237) block strikes back (https://github.com/jellyfin/jellyfin/issues/5576#issuecomment-809645719). I see through Wireshark that my NU7400 (Tizen 4) requests HEVC stream, but cannot switch stream to HEVC and keeps playing the H264 fallback stream.

Removing mentioned block fixes issue.

**Comment by ApexArray** [comment]
Interesting. Kudos for busting out Wireshark to get the details.

I read through the issue and understand the need for backwards-compatibility, but I'd love to get this working without needing to run a dev version of JF indefinitely. Is this expected to be fixed in an upcoming version, or is the issue still stuck?

If stuck, is there anything we can report in the device profile that would indicate whether this block is necessary? Or perhaps we could add an advanced user setting to toggle this block of code?

**Comment by bsod-haunted** [comment]
Hi,
it has been a while, but i can report that at least for my TV the issue is relsolved.
I noticed that playback now does work fine with HDR 4K files, as long as there are no subtitels used in the file. I will open another issues for that though.
Can anyone else confirm this, so this issues can be marked as resolved?

**Comment by dmitrylyzo** [comment]
In theory, `HEVC HDR + TRUEHD/DTS` with HEVC encoding enabled (server settings) causes unnecessary video transcoding (to SDR) as a fallback stream.
