### ISSUE TITLE
After full closing/shutting down tv and relaunching Jellyfin, Infinite loading happens on the login screen

### ISSUE THREAD

**Issue by Sakooooo** [jellyfin/jellyfin-tizen#169]
I have tried reinstalling it and using a bunch of older issues and none of them seem to work.
The only fix was to restart the server and then wait for it to get onto the server select screen then login to that server.

**Comment by dmitrylyzo** [comment]
Same? https://github.com/jellyfin/jellyfin-tizen/issues/59#issuecomment-1374571904

**Comment by Sakooooo** [comment]
> Same? https://github.com/jellyfin/jellyfin-tizen/issues/59#issuecomment-1374571904

will try to rebuild jellyfin-tizen with jellyfin-web 10.8 but yeah same issue

**Comment by Sakooooo** [comment]
yup that fixed it, it would be a nice idea to add instead of cloning jellyfin-web we download the src of the latest jellyfin-web in the releases tab thanks for the help

**Comment by Sakooooo** [comment]
(i could by chance make a pr to modify the readme maybe)

**Comment by dmitrylyzo** [comment]
I'm leaning more towards locking the jellyfin-web version in the jellyfin-tizen repo and build all at once. But at the same time jellyfin-web should be interchangeable.

**Comment by Sakooooo** [comment]
> I'm leaning more towards locking the jellyfin-web version in the jellyfin-tizen repo and build all at once. But at the same time jellyfin-web should be interchangeable.

yeah makes sense, i remember someone mentioning github actions to make releases or just having an already compiled release ready to be delivered until samsung actually accepts the app

but for now it would probably be best to inform in the readme that you must use a version FROM the releases tab until jellyfin-tizen and jellyfin-web become on repo with everything but thats a good idea

if i could i could figure out how to make a simple npm command that does everything for you via cmd but i have never really touched tizen studio or the cli so it might take awhile
