### ISSUE TITLE
The term 'tizen' is not recognised as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by samsunger** [jellyfin/jellyfin-tizen#180]
I can figure out what to do here i followed the youtube video guide and in the video everything works fine but for me i get this error

![image_2023-02-11_025612133](https://user-images.githubusercontent.com/125102113/218228406-3e911a2f-761f-41e0-b643-807d2a0dd557.png)

**Comment by dmitrylyzo** [comment]
https://github.com/jellyfin/jellyfin-tizen/issues/154#issuecomment-1317265462
https://github.com/jellyfin/jellyfin-tizen/issues/55#issuecomment-752195367

**Comment by samsunger** [comment]
I tried writing it as tizen.bat but it gives me this error and says i should use .\tizen.bat but when i use it this happens

![image_2023-02-11_115633331](https://user-images.githubusercontent.com/125102113/218251872-79eb88a2-daf2-49c8-961a-346a547b3db4.png)

**Comment by samsunger** [comment]
Okay i think i managed to fix it? Because my tizen folder is called tizen sdk and it has a space so windows only checks out e:/tizen
I renamed the folder to tizensdk and i think it did it

![image_2023-02-11_121324952](https://user-images.githubusercontent.com/125102113/218252537-6b0997b0-d6ad-48c0-9ffe-77a33c639e91.png)

**Comment by samsunger** [comment]
After continuing to follow the tutorial im trying to start up tizen device manager but nothing happens now lol. tizen studio doesnt open too

**Comment by samsunger** [comment]
Opened package manager first let it load and that fixed it for me

**Comment by samsunger** [comment]
device manager opens for a split second and closes, tizen studio just doesnt do anything after choosing the workspace folder. i installed tizen again on a different folder and it opens so i think i fucked something up

**Comment by samsunger** [comment]
Okay idk if anyone needs this but i fixed it by renaming my folder back to tizen sdk from tizensdk and now it opens lol

**Comment by samsunger** [comment]
Well.. i thought those were all my problems but here i am again. When pressing install app on device manager and choosing the file it shows this loading thing and then nothing. i check the tv and there is no app too.

![image_2023-02-11_131726801](https://user-images.githubusercontent.com/125102113/218255117-eea34be0-c57b-4cbd-b628-89a927a9f471.png)

**Comment by samsunger** [comment]
and if i do it with the command this shows up

![image_2023-02-11_132226744](https://user-images.githubusercontent.com/125102113/218255311-898c6a72-f78b-43de-8d68-2482a94c7e7d.png)

**Comment by samsunger** [comment]
and again i have to remove the space between tizen sdk name that i made before starting all this because tizen programs stop working

**Comment by samsunger** [comment]
Okay i started over again and it works now i think because i was doing it yesterday at 3 A.M. i just skipped some point in the video lol. Thanks for help:3
