### ISSUE TITLE
Remotes play button doesn't work

### ISSUE THREAD

**Issue by Aasikki** [jellyfin/jellyfin-tizen#183]
The play button on my remote doesn't do anything in jellyfin, it just shows a picture of the remotes navigation buttons with media icons overlayed on it. For example on YouTube, the button will pause/unpause the playback as expected, but in jellyfi, I have to highlight and press the play button from the GUI using the remotes navigation keys.

Can post a video and pictures later if my explanation wasn't clear enough!

**Comment by dmitrylyzo** [comment]
> shows a picture of the remotes navigation buttons with media icons overlayed on it.

That's how it's meant to be.
According to this overlay, you need to press the center button to Play/Pause.

**Comment by Aasikki** [comment]
> > shows a picture of the remotes navigation buttons with media icons overlayed on it.
> 
> That's how it's meant to be. According to this overlay, you need to press the center button to Play/Pause (when the hint is displayed).

No I believe that's for apps/devices that don't support the pause button correctly. It works fine and directly pauses the video on other apps like YouTube. Only other place where I get that overlay is on hdmi devices like my Chromecast. Also if I do press the buttons as guided by the overlay, jellyfin still won't respond.

**Comment by Aasikki** [comment]
Checked again and actually the overlayed buttons work fine in jellyfin. I still think the correct way would be to pause the video directly, like other apps do. It's cumbersome to have to press multiple buttons just to quickly pause what you're watching.

Anyway here's a quick video on how it behaves in a couple other apps vs jellyfin
https://youtu.be/LOxeZeBdmZg

**Comment by Aasikki** [comment]
The fix works perfectly!
