### ISSUE TITLE
Samsung Q90 cannot deselect filter

### ISSUE THREAD

**Issue by specter42** [jellyfin/jellyfin-tizen#185]
Compiled for Samsung Q90. When activating filter in library like '#" I can not deselect it. Tried with samsung remote and USB keyboard. The app is completly useless now and I cannot reset the filter.

**Comment by dmitrylyzo** [comment]
Doesn't clicking on the same filter deactivate it?

**Comment by specter42** [comment]
> Doesn't clicking on the same filter deactivate it?

Nope, thats exactly the problem. Clicking with the samsung remote again on the same filter does not deactivate it. I'm talking about the letters on the right edge. So the situation is, i clicked on the numbers '#' filter. It only shows me movies starting with numbers. Clicking again does not deactivate it. Clicking on another letter shows nothing. The '#' filter is still active. Clicking again on the numbers filter shows again only movies starting with numbers. Result -> I can only see movies starting with numbers :(

**Comment by dmitrylyzo** [comment]
Which branch of jellyfin-web was used? 10.8 or master
_AlphaPicker works fine in 10.8.9 in Tizen 3/5/6 emulators._

**Comment by specter42** [comment]
git clone https://github.com/jellyfin/jellyfin-web.git

**Comment by dmitrylyzo** [comment]
So this is `master`.
I recommend to use 10.8.9 for the stable server. The `master` is not stable because it is migrating to React.
Use `git checkout release-10.8.z` in the `jellyfin-web` folder (or `git clone -b release-10.8.z https://github.com/jellyfin/jellyfin-web.git` if you go from scratch) and rebuild web, then rebuild app.

**Comment by specter42** [comment]
Thanx! I will try and come back.

**Comment by specter42** [comment]
Hi! Compiled with 10.8.9 and it fixed it! Thanx a lot! I should have read the instructions better :) Cheers!
