### ISSUE TITLE
blackscreen when launching app

### ISSUE THREAD

**Issue by lojziczech** [jellyfin/jellyfin-tizen#186]
hi, I successfully build and installed jellyfin on my tv but when I try to launch it shows a black screen indefinitely.
tv model: UE55M6372
platform tv-3.0

**Comment by dmitrylyzo** [comment]
At least, 10.8.9 (which is recommended for the stable server) works in the Tizen 3 emulator.
The last time I checked the master branch was also working, iirc.

**Comment by lojziczech** [comment]
i downloaded the 10.8.z version of the jellyfin-web and latest version of jellyfin-tyzen

**Comment by lojziczech** [comment]
somehow got it to work, thanks for the reply
