### ISSUE TITLE
can base on jellyfin-vue?

### ISSUE THREAD

**Issue by Ritchie1108** [jellyfin/jellyfin-tizen#193]
is it possible to use jellyfin-vue to replace jellyfin-web?

https://github.com/jellyfin/jellyfin-vue

**Comment by Ritchie1108** [comment]
maybe can use this fork
https://github.com/gibahjoe/jellyfin-vue/tree/lgtv

**Comment by dmitrylyzo** [comment]
1. AFAIK, `jellyfin-vue` is targeting modern browsers, so it may not work on older TVs.
2. Its UI is designed mainly for Desktop/Mobile (layout, card size, font size, etc.).
3. TV requires spatial navigation, which seems to have been added in the fork you mentioned (_I haven't tested_).

**Comment by thornbill** [comment]
Yes the Vue project targets newer browsers and Vue 3 specifically uses features that cannot be supported by the browsers shipped in older Tizen and webOS versions so this is not possible.

**Comment by scottf007** [comment]
has anyone tested this? 

according to this - TVs since 2018 it should work : **https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html**

https://caniuse.com/es6
