### ISSUE TITLE
Transcode Audio to AC3 instead of AAC

### ISSUE THREAD

**Issue by kraM1tt** [jellyfin/jellyfin-tizen#204]
Hi, I have a Sony HTIAB, it only supports PCM, Dolby Digital (AC3) and Dolby Digital Plus (EAC3). I sometimes have files with only DTS or TrueHD audio, the problem is Jellyfin FFMPEG only transcodes the audio to AAC which is unsupported and causes VERY low audio volume playback vs if I pre-transcode it to AC3 myself. Of course that's very time consuming, transcoding then remuxing. Is there any way I can tell JF-FFMPEG to transcode to AC3 instead? I dug around all of the Jellyfin installation directory, found a few .xml files with lots of AAC references inside but no clue how to go about it.

Is there a way of modifying the Tizen client to call for AC3 instead of AAC myself?

Thanks

**Comment by dmitrylyzo** [comment]
> Is there any way I can tell JF-FFMPEG to transcode to AAC instead?

Did you mean "to AC3"?

> I dug around all of the Jellyfin installation directory, found a few .xml files with lots of AAC references inside but no clue how to go about it.

Those are DLNA profiles - they aren't used by WEBUI.

> Is there a way of modifying the Tizen client to call for AC3 instead of AAC myself?

There is currently no way to set the codec priority using UI. Try [this patch](https://github.com/dmitrylyzo/jellyfin-web/commit/56f234bc18ebc56b95753524171f81fef9a82eac) for WEBUI - you need to rebuild the app.

**Comment by kraM1tt** [comment]
Sorry yes I meant AC3, I'll edit, ty for the patch but I have no clue how to implement it haha sorry

**Comment by drspangle** [comment]
@dmitrylyzo Does your path for WEBUI potentially fix the issue I'm having in #226 ?

**Comment by dmitrylyzo** [comment]
> @dmitrylyzo Does your patch for WEBUI potentially fix the issue I'm having in #226 ?

Unlikely, my patch (in fact, a test) is only intended to prioritize audio codec when transcoding.

**Comment by gnattu** [comment]
May I ask for a clarification of the problem? Does the Videos with stereo (2 channels) aac also suffers from this low volume issue? Or it only happens to 5.1 channel audios.
