### ISSUE TITLE
Unable To Connect To Server

### ISSUE THREAD

**Issue by Orbitally** [jellyfin/jellyfin-tizen#207]
Hi! I'm running into an issue where when entering the server address and clicking connect it comes back with an error saying `We're unable to connect to the selected server right now. Please ensure it is running and try again`. 

I've tried using `http://<address>:8096` as well as just `<address>:8096` in both the app and the browser with neither of them working

The server seems to be working as it should since I can connect to it from any other device. This is just a local server and anything connecting to it is within the LAN. I also tried connecting to the server from the TV's web browser and that also isn't able to connect and just returns an error saying it couldn't connect to the page. Thanks in advance!

**Comment by dmitrylyzo** [comment]
Is there any error in the server log?
Or any mark that the TV is trying to access?

Do both, the server and the web used for the app, have the same version (10.8.10)?

**Comment by Orbitally** [comment]
> Is there any error in the server log? Or any mark that the TV is trying to access?

Looking at the logs from the Docker container after trying to connect nothing new shows up. It's strange though since checking the admin dashboard it shows up as a device that was previously active so I'd imagine that it's connecting somehow for a second.

> Do both, the server and the web used for the app, have the same version (10.8.10)?

I built the app for the TV using the `release-10.8.z` branch from the `jellyfin-web` repo and the server says it's on version `10.8.10`

**Comment by dmitrylyzo** [comment]
> Looking at the logs from the Docker container after trying to connect nothing new shows up.

First, you need to find out if the server is accessible from the TV.
I have no experience with networking in the Docker, but from what I've heard, it can be tricky.
At the same time, you said that other clients work. 🤷‍♂️ 

Btw, is this your first time setting up a server in the app?
Webui clients remember the server id, and the new server refuses connections with the old id. In this case, you need to remove and then re-add the server in the client.

**Comment by Orbitally** [comment]
So turns out that trying to do this while being very sleep deprived and tired isn't the best idea... Wasn't thinking straight and was just putting in the wrong server address. Thanks for the help!
