### ISSUE TITLE
Cannot control after restart

### ISSUE THREAD

**Issue by pbogre** [jellyfin/jellyfin-tizen#210]
Currently I have to reinstall the application using tizen studio every time i want to re-open it :/

When i first install and and open it, I am perfectly able to use the remote to control the selected option, however when i turn off the tv or need to reopen jellyfin when it wasn't running in the background, the home menu loads and i'm stuck because i cannot select anything and it doesn't look like anything is currently selected.

I built the latest jellyfin-web repository and followed every step on the readme except creating certificates (the applications opens fine anyway though), because I wasn't able to do that since trying to make tizen studio gui run on my mac feels like trying to insert a plumbing tube up my urethra

I also noticed in jellyfin that I get the following error when closing the client from my TV, which i dont get from other clients:
```
Emby.Server.Implementations.HttpServer.WebSocketConnection: WS {ip} error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
```

I was getting this same error when a stream kept freezing and then crashing unless i stopped using external subtitles (and therefore had to transcode) which i guess could be an issue of its own but i just worked around it by transcoding the movie

**Comment by dmitrylyzo** [comment]
What TV model?

> latest jellyfin-web

Do you mean the `master` branch? Or `release-10.8.z`?

**Comment by kraM1tt** [comment]
Try using this pre-built version, worked perfect for me so far on multiple TV's, and only require the CLI

https://github.com/jeppevinkel/jellyfin-tizen-builds

**Comment by pbogre** [comment]
i tried the prebuilt package at first but got the same error. 

the package i built myself was with the master branch of jellyfin-web.

However i found that this is a hardware-specific issue, because when i installed the same package on another tv it was perfectly able to load movies on boot and that allowed me to control it. perhaps it's something related to the networking, since the tv it worked on fine was using ethernet while the other is on wifi. 

anyway, i'll close this issue as it's not really related to the repository but rather my fault with the setup.
