### ISSUE TITLE
SSL / TLS / https connection to server is not possible (letsentcrypt certificate)

### ISSUE THREAD

**Issue by gibso** [jellyfin/jellyfin-tizen#223]
Hello fellow developers,

I have a jellyfin server instance running with the very latest version. I am serving the server with a valid letsentcrypt certificate on port 443. On port 80 there's just a redirect to port 443, as it is conventional to me with web server apps.

Via the web client I can login to jellyfin and everything works. With the Android App  on my phone I can connect to the server as well just fine. But with the tizen app it just says to me after a second something like "connection not possible / can't connect to server".

However, when I open another port on my server and serve jellyfin without certificate, unencrypted via http, the tizen app can connect successfully to that port. That leads to my suspicion that the tizen app maybe doesn't accept letsentcrypt certificates.

Does anyone know more of this?

Thanks so much!

**Comment by dmitrylyzo** [comment]
Probably dup #161

If your TV is Tizen 2.x, it has an expired root certificate and I don't know if it can be updated.

**Comment by gibso** [comment]
This is a very good explanation, that TV is indeed a wee bit older. Thanks! I close this then, since there is nothing we can do about this on the app.
