### ISSUE TITLE
Trouble with Windows Build

### ISSUE THREAD

**Issue by ClemKristian** [jellyfin/jellyfin-tizen#225]
Seem to have an issue building this. I am able to compile jellyfin-web but not jellyfin-tizen. I get the error as shown plus a lot of depreciated errors npm logs are included. Any help would be greatly appreciated.

![image](https://github.com/jellyfin/jellyfin-tizen/assets/45670323/8ecc4d7d-bd3d-4a58-b8c7-c48622c924bc)
[2023-10-15T22_34_19_975Z-debug-0.log](https://github.com/jellyfin/jellyfin-tizen/files/12910819/2023-10-15T22_34_19_975Z-debug-0.log)

**Comment by thornbill** [comment]
Did you build jellyfin-web first?

**Comment by SebastienBenazet** [comment]
I have the same issue.
Building it on Windows 10, using Powershell. I followed the steps, build jellyfin-web-10.8.11 but I can't build jellyfin-tizen.
