### ISSUE TITLE
Video not playing on Tizen OS 3.0 smart TV

### ISSUE THREAD

**Issue by Ahamedo** [jellyfin/jellyfin-tizen#23]
Hello,

I installed the latest app on my TV and when trying to play any movie, the spinner appears and it just keep spinning without playing the movie.

Thank you

**Comment by dmitrylyzo** [comment]
Probably the same as #20 
If you used jf-web before https://github.com/jellyfin/jellyfin-web/commit/c23e301e32c1fc036239f7a9630c2409ebe13f52 just pull jf-web again.

**Comment by Ahamedo** [comment]
Yes that fixed it. thank you very much
