### ISSUE TITLE
Error After Completing Setup

### ISSUE THREAD

**Issue by alasfarm** [jellyfin/jellyfin-tizen#232]
![403920254_1488499335214589_4088998813235541992_n](https://github.com/jellyfin/jellyfin-tizen/assets/70985535/e93575cc-ceff-461e-b161-8dda50c43411)

**Comment by dmitrylyzo** [comment]
The current `jellyfin-web:master` branch is not suitable for older web engines. Use the `release-10.8.z` branch.
