### ISSUE TITLE
Windows Build error

### ISSUE THREAD

**Issue by aaronmee** [jellyfin/jellyfin-tizen#233]
Hi,
I want to build jellyfin-web on windows for my samsung smart tv. 
But I receive an error when trying to build jellyfin-web using "npm run build:production". 

I have node.js 20.10.0 LTS installed, npm is up to date. 
At the end of the build process I get this line: webpack 5.70.0 compiled with 1 error and 1 warning in 38751 ms
The error is this: ERROR in ./components/images/blurhash.worker.ts \ Module build failed (from ../node_modules/worker-loader/dist/cjs.js):

I followed the build on windows guide exactly, but sadly it didn't work.

Any help is appreciated!

Regards

**Comment by dmitrylyzo** [comment]
NodeJS 20.10.0 + NPM 10.2.4
![jeff-1](https://github.com/jellyfin/jellyfin-tizen/assets/56478732/91ccf485-3ba7-4773-a10d-42fe07e20c56)

Make sure that the modules are installed correctly.

**Comment by aaronmee** [comment]
npm: 10.2.4
Node.js: v20.10.0

Commands:
- git clone -b release-10.8.z https://github.com/jellyfin/jellyfin-web.git
- cd jellyfin-web
- set SKIP_PREPARE=1
- set DISCARD_UNUSED_FONTS=1
- npx update-browserslist-db@latest
- npm ci --no-audit
- npm run build:production

Output:
![grafik](https://github.com/jellyfin/jellyfin-tizen/assets/114234515/e5dacd3d-9c00-4f04-a2d2-5d4c071cf9db)

**Comment by aaronmee** [comment]
# Update:

I resolved the issue with installing yarn: `npm install --global yarn`

It's working now!

**Comment by aaronmee** [comment]
Closing this
