### ISSUE TITLE
install failed[118] on UE58MU6125 (Tizen 3.0)

### ISSUE THREAD

**Issue by klnstprx** [jellyfin/jellyfin-tizen#243]
Hi, 
I'm trying to install jellyfin on my Samsung UE58MU6125 with Tizen 3.0. 

Using Ubuntu 23.10.

This is the error I'm getting

```
❯ ~/tizen-studio/tools/ide/bin/tizen install -n Jellyfin.wgt -t UE58MU6125
Transferring the package...
Transferred the package: /home/klnstpr/jellyfin-tizen/Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt
was_install_app return WAS_TRUE
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] install failed[118]
spend time for wascmd is [9301]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:19.299

```

The PC is connected with the TV via "Device Manager":
![image](https://github.com/jellyfin/jellyfin-tizen/assets/91422338/153a8072-742a-44ff-879b-600935bbf70a)

I have also clicked the "Permit to install applications button":
![image](https://github.com/jellyfin/jellyfin-tizen/assets/91422338/6b2f5e26-d4e0-43c7-99ac-eede55870f38)

Things I've already tried doing:

- updating the TV OS (EOL, no new updates since forever)
- building the .wgt with both Tizen and Samsung certificates: ![image](https://github.com/jellyfin/jellyfin-tizen/assets/91422338/ce65c6c3-7406-49f7-ad45-7ef679e1317d)
- uploading the prebuilt .wgt from: https://github.com/jeppevinkel/jellyfin-tizen-builds/releases?page=1
- using the single line docker install from: https://github.com/Georift/install-jellyfin-tizen

Every single attempt ended with "install failed [118].

The TV is in developer mode, with the correct IP addr of my PC.
I also tried running the docker command from a different machine, resulting in the same error.

**Comment by dmitrylyzo** [comment]
_from https://developer.youi.tv/6.1/Content/Tizen_DevTopics/H1BuildingInstallingAppWidgets.htm_
> Device is either out of space and does not have enough room to install your widget, or it is already installed. Possible cause include:
>
>    - There could be an issue with your Tizen config.xml manifest file.
>    - This device requires a Samsung certificate instead of a Tizen certificate.
>    - Your device is not whitelisted in your Samsung certificate.
>    - There may be restricted privileges or trust anchors in your Tizen config.xml manifest file.
>
> On some TV’s, the 118### sub-errors are often generalized into a 118 error, so it can often be difficult to track down the root cause of the error.

Also, when building using a Samsung certificate, you need to `Permit install` from the Device Manager (right-click on the connected TV) first.

**Comment by klnstprx** [comment]
> _from https://developer.youi.tv/6.1/Content/Tizen_DevTopics/H1BuildingInstallingAppWidgets.htm_
> 
> > Device is either out of space and does not have enough room to install your widget, or it is already installed. Possible cause include:
> > 
> > * There could be an issue with your Tizen config.xml manifest file.
> > * This device requires a Samsung certificate instead of a Tizen certificate.
> > * Your device is not whitelisted in your Samsung certificate.
> > * There may be restricted privileges or trust anchors in your Tizen config.xml manifest file.
> > 
> > On some TV’s, the 118### sub-errors are often generalized into a 118 error, so it can often be difficult to track down the root cause of the error.
> 
> Also, when building using a Samsung certificate, you need to `Permit to install applications` from the Device Manager (right-click on the connected TV) first.

Yep, I forgot to mention that I already did that, and saw that page. Still the same error. The config.xml was not touched; I think the TV has enough storage space, since only a handful of applications were installed (I uninstalled some of them to confirm that), no photos, videos or any files whatsoever should be stored on the TV.

**Comment by mrld341** [comment]
For me it didn't install, until I had 250+MB free. 
Had to delete some default apps...

**Comment by klnstprx** [comment]
> For me it didn't install, until I had 250+MB free. Had to delete some default apps and reset TV to default settings.

This might just be the case. The TV has 700MB of memory, only 59MB being free. How did you delete the default apps? Is there any way to increase the storage capacity? (I plugged in a usb drive and it doesn't seem to have done anything.)

**Comment by klnstprx** [comment]
Managed to free 236MB by deleting some default apps with the following commands:
Listing all apps:
`sdb shell 0 vd_applist `
Deleting:
`sdb shell 0 vd_appuninstall <id>`

Still encountering the same error:
```
❯ ./tizen install -n ~/jellyfin-tizen/Jellyfin.wgt -t UE58MU6125
Transferring the package...
Transferred the package: /home/klnstpr/jellyfin-tizen/Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt
was_install_app return WAS_TRUE
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[8]
app_id[AprZAARz4r.Jellyfin] installing[11]
app_id[AprZAARz4r.Jellyfin] installing[14]
app_id[AprZAARz4r.Jellyfin] installing[17]
app_id[AprZAARz4r.Jellyfin] installing[20]
app_id[AprZAARz4r.Jellyfin] installing[22]
app_id[AprZAARz4r.Jellyfin] install failed[118]
spend time for wascmd is [12466]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:18.427

```

**Comment by klnstprx** [comment]
Success. I decided to try the 1 command docker again, and it worked.
https://github.com/Georift/install-jellyfin-tizen
