### ISSUE TITLE
Prepare Interface fails with TypeError

### ISSUE THREAD

**Issue by conormarkmurphy** [jellyfin/jellyfin-tizen#244]
node@60fdb3368f92:/home/eeicmuy/tmp/jellyfin-tizen$ npm -v
10.5.1
node@60fdb3368f92:/home/eeicmuy/tmp/jellyfin-tizen$ node -v
v22.0.0
node@60fdb3368f92:/home/eeicmuy/tmp/jellyfin-tizen$ JELLYFIN_WEB_DIR=../jellyfin-web/dist npm ci --no-audit
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated abab@2.0.5: Use your platform's native atob() and btoa() methods instead
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated domexception@1.0.1: Use your platform's native DOMException instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies

> jellyfin-tizen@0.1.0 postinstall
> gulp

Using jellyfin-web from /home/eeicmuy/tmp/jellyfin-web/dist
(node:100) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[13:48:58] Using gulpfile /home/eeicmuy/tmp/jellyfin-tizen/gulpfile.js
[13:48:58] Starting 'default'...
[13:48:58] Starting 'clean'...
[13:48:58] Finished 'clean' after 6.74 ms
[13:48:58] Starting 'searchFonts'...
[13:48:58] Finished 'searchFonts' after 567 μs
[13:48:58] Starting 'copy'...
[13:48:58] Starting 'modifyIndex'...
Found injected main.bundle
[13:48:58] 'modifyIndex' errored after 137 ms
[13:48:58] TypeError: Cannot assign to read only property 'atime' of object '#<Stats>'
    at onFutimes (/home/eeicmuy/tmp/jellyfin-tizen/node_modules/vinyl-fs/lib/file-operations.js:258:27)
    at FSReqCallback.oncomplete (node:fs:188:23)
    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)
[13:48:58] 'default' errored after 148 ms
npm ERR! code 1
npm ERR! path /home/eeicmuy/tmp/jellyfin-tizen
npm ERR! command failed
npm ERR! command sh -c gulp

**Comment by dmitrylyzo** [comment]
This is a regression in NodeJS: https://github.com/nodejs/node/issues/52707 It seems to be fixed in the next release.
I recommend you to use NodeJS 20/21.

**Comment by conormarkmurphy** [comment]
Builds okay with NodeJS/21. Thanks
