### ISSUE TITLE
Media stop playing, server unavailable

### ISSUE THREAD

**Issue by makakam83** [jellyfin/jellyfin-tizen#259]
Hi

With the latest 10.9.1 release and the latest jeppevinkel build my Tizen app has stopped playing a couple of times now and when it does the server seems to be stalled and can not be accessed until I restart the container. Anyone has the same issue? It did not happen even once before the update.

Can't find any info in logs related to it.

**Comment by indiependente** [comment]
This started happening to me recently even with an older build. I will post the build number when I'll have access to the tv.

**Comment by makakam83** [comment]
Just updated to 10.9.2 and will update jeppevinkel's app today. Hope this resolved the issue

**Comment by makakam83** [comment]
Haven't experienced this since back then so it must have been fixed. This issue can be closed.
