### ISSUE TITLE
Server connection issue

### ISSUE THREAD

**Issue by aaronmee** [jellyfin/jellyfin-tizen#262]
Hi,
I'm running a jellyfin instance on my raspberry pi and want to stream my library to my tv. For the past 3 months that worked like a charm, but now it suddenly stopped working. My tv just isn't able to connect to my server anymore. Here' an image of the error message:

![WhatsApp Bild 2024-05-21 um 19 24 45_5f909108](https://github.com/jellyfin/jellyfin-tizen/assets/114234515/06469d01-14cd-4a19-8d8c-5fddf3ab97b1)

Accessing it with the mobile application and the browser is working, so I guess the issue is on the tv side. I just installed the newest version `10.9.2` on the tv, but the issue is still there. 
The server is running as a `linuxserver.io docker container` on a `raspberry pi 5`. The server version is `10.9.2`
Any help is appreciated

**Comment by aaronmee** [comment]
Doesn't it try different combinations like the android app does? If no then this is probably the issue...
It's running on default port 8096

**Comment by dmitrylyzo** [comment]
AFAIK, it only tries http/https, not the port. Have you tried entering the port?

**Comment by aaronmee** [comment]
Yes, entering the ports works. Forgot that this was needed...
Closing this, thank you
