### ISSUE TITLE
Add max channel setting

### ISSUE THREAD

**Issue by SaltySP** [jellyfin/jellyfin-tizen#274]
Jellyfin added new audio downmix algorithms in 10.9. I think it would be great to have an option to configure the max channels, especially for night playback. The user setting for max channels is ignored as it only applies for transcoding, not direct play. I tried editing the device profile but was unable to get any working results. Even if I was successful, it would then "always" downmix which would also not be a perfect/permanent solution.

**Comment by dmitrylyzo** [comment]
The app is just a wrapper. Everything that is implemented in Jellyfin Web is available in the app after rebuild.

**Comment by SaltySP** [comment]
Ok, I'll post this in the jellyfin web repo. Thanks

**Comment by dmitrylyzo** [comment]
Hmm. Tbf, I thought it worked for DirectPlay as well, but looking at the code, it doesn't.
I just move this to web.
