### ISSUE TITLE
After install, only header with current time is displayed

### ISSUE THREAD

**Issue by ilteoood** [jellyfin/jellyfin-tizen#279]
I have an old Samsung tv, model UE43KU6400UXZT.
With jellyfin-tizen version 10.8.z everything works fine, but if I try to install the latest version 10.9.8 I can only see the header with the current time displayed in the right side, but nothing else.

According to https://github.com/jellyfin/jellyfin-tizen/issues/258 it should be already fixed, but in my case is still happening. Maybe the tv model is too old to still be supported?

**Comment by dmitrylyzo** [comment]
I tested pre-10.9.8 (_not the final state though_) in the webOS 1.2 emulator (~Tizen 2.3) and it worked fine.

Have you tried uninstalling the app first?

I've encountered an authentication issue where the token seems to be invalid, but the web doesn't redirect to the login page. The home page looked just as you described, iirc. The only way I know of to reset an app's cache is to uninstall it.

**Comment by ilteoood** [comment]
Yes I uninstalled it first, because I had a conflict on the certificate. I installed one of the pre built versions from a repository I've found that builds them every day. Could it be that?
I would like to debug it by myself but I'm not able to download an emulator for such an old version, and I can't debug the version running on my tv either.

If you could give me some hints I would be more than happy to help

**Comment by dmitrylyzo** [comment]
> Yes I uninstalled it first, because I had a conflict on the certificate. I installed one of the pre built versions from a repository I've found that builds them every day. Could it be that?

AFAIK, they generate a certificate on every build, so it may cause a certificate conflict.

> I would like to debug it by myself but I'm not able to download an emulator for such an old version, and I can't debug the version running on my tv either.

There's no emulator for Tizen 2.x.

> If you could give me some hints I would be more than happy to help

Look here: https://github.com/jellyfin/jellyfin-tizen/issues/79

**Comment by ilteoood** [comment]
Hi @dmitrylyzo,
I've been able to follow the thread and view some logs.
Here is the output I can read from the console:
```
Viewport argument key "viewport-fit" not recognized and ignored. index.html:3
Tizen adapter tizen.js:4
it-IT
[dateFnsLocale] updating date-fns locale it-it
[dateFnsLocale] mapped to date-fns locale it
AppHost.init 
Object
 tizen.js:80
AppHost.getDefaultLayout tv tizen.js:80
ReferenceError: Strict mode forbids implicit creation of global property 'DocumentScroller'
[productinfo.js] isUDPanelSupported  begin /opt/down/pepper/webapis/webapis.js:1306
[productinfo.js] isUDPanelSupported  end [object Object] /opt/down/pepper/webapis/webapis.js:1312
[productinfo.js] isUDPanelSupported message data true /opt/down/pepper/webapis/webapis.js:1316
4K UHD is supported 
```

I guess the major issue is:
```
ReferenceError: Strict mode forbids implicit creation of global property 'DocumentScroller'
```
as I don't see this error if I build using the branch `release-10.8.z`

**Comment by ilteoood** [comment]
I've tried chaning the common webpack config by inserting `minimize: false` and also changing in the dev config `devtool: 'inline-source-map' and re-install everything. Now I have a better error message (which is completely different than before)
```
Matched leaf route at location "/" does not have an element or Component. This means it will render an <Outlet /> with a null value by default resulting in an "empty" page. [node_modules.@remix-run.router.6a1b4fa0b92004def324.chunk.js:490](file:///opt/usr/apps/AprZAARz4r/res/wgt/www/node_modules.@remix-run.router.6a1b4fa0b92004def324.chunk.js)
```

**Comment by burci** [comment]
Hi,

I have the same issue (only one line on the top with the time). I have a Samsung UE49KS7000, it has Tizen 2.4.

I tested today with https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/download/2024-08-10-0334/Jellyfin-master.wgt and the problem still exists.

**Comment by ilteoood** [comment]
Can you try building with my patch and test if it works?
If it also works for you, we can ping the solution to be merged.

**Comment by burci** [comment]
Yes, I tried out and the https://github.com/jellyfin/jellyfin-web/pull/5823 solved the problem.

**Comment by formeo14** [comment]
Works! Thank you!

**Comment by ilteoood** [comment]
This should be fixed now, has been merged in the release branch
