### ISSUE TITLE
donation?

### ISSUE THREAD

**Issue by jlevon** [jellyfin/jellyfin-tizen#281]
https://opencollective.com/jellyfin/updates/were-good-seriously

Suggests we should donate to client authors instead. Can somebody suggest how, or who? Thanks!

**Comment by wrgallo** [comment]
The fact this issue is still open and "Tizen" is not even listed in the [jellyfin-team](https://github.com/jellyfin/jellyfin-meta/blob/master/jellyfin-team.md) is actually concerning, it does look like this client is no longer being maintained.

May @nielsvanvelzen update the file?

**Comment by nielsvanvelzen** [comment]
The Tizen client is 99% jellyfin-web with a few support files for the platform, as such it's not mentioned on that list. The primary person from our team contributing to Tizen and WebOS support is @dmitrylyzo, with @anthonylavado doing publishing & paperwork. Additionally @thornbill is the person who leads the jellyfin-web project.

You can look at all contributors for both repositories on GitHub:
- https://github.com/jellyfin/jellyfin-tizen/graphs/contributors
- https://github.com/jellyfin/jellyfin-web/graphs/contributors
