### ISSUE TITLE
tizen command not found

### ISSUE THREAD

**Issue by moeinrahimi** [jellyfin/jellyfin-tizen#282]
in step building jeyllyfin-tizen i can't run tizen build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock" beacuse tizen command is not found. both tizen studio ide and cli are installed

**Comment by dmitrylyzo** [comment]
Just use full path: `~/tizen-studio/tools/ide/bin/tizen`
On my PC, it is added to `PATH` environment variable.
