### ISSUE TITLE
Can not deploy to TV

### ISSUE THREAD

**Issue by Basti-Fantasti** [jellyfin/jellyfin-tizen#285]
Hi,

I followed the instruction and succeeded in all steps except the installation to the TV.

- I use a Tizen cert for the deployment.
- building of all modules using npm succeeded
- building the package using tizen worked

When running the install command I get this error:

```
 tizen install -n .\Jellyfin.wgt -t QE65Q7FGM
Transferring the package...
Transferred the package: C:\git_local\jellyfin-tizen\Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin

package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt

was_install_app return WAS_TRUE

app_id[AprZAARz4r.Jellyfin] install start

app_id[AprZAARz4r.Jellyfin] installing[8]

app_id[AprZAARz4r.Jellyfin] installing[11]

app_id[AprZAARz4r.Jellyfin] installing[14]

app_id[AprZAARz4r.Jellyfin] installing[17]

app_id[AprZAARz4r.Jellyfin] installing[20]

app_id[AprZAARz4r.Jellyfin] installing[22]

app_id[AprZAARz4r.Jellyfin] install failed[118]

spend time for wascmd is [3578]ms

cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:08.097
```

any ideas?

**Comment by dmitrylyzo** [comment]
`118` is a certificate error.
But first check if you have enough free space on your TV.
If there is enough free space, you probably need to use a Samsung certificate (this requires a Samsung account).

**Comment by Basti-Fantasti** [comment]
Thanks for commenting. In the meantime I got the package loaded using the docker approach.
So I think you're right and it was in any way related to the certificate.
