### ISSUE TITLE
Secondary subtitle not working on my Samsung TV

### ISSUE THREAD

**Issue by Xcellion** [jellyfin/jellyfin-tizen#300]
Hello,

I installed the official Jellyfin app using the docker method (https://github.com/Georift/install-jellyfin-tizen)

And I am able to stream movies perfectly. However, I noticed that the secondary subtitle function doesn't work. The option to select a secondary sub is there, but only one language ever appears.

When I select a second language, it just overwrites the main language.

Can anyone help?

**Comment by dmitrylyzo** [comment]
Tizen app uses `HTMLVideoElement`. On Tizen 5 (tested with emulator) it doesn't seem to support simultaneous display of multiple text tracks. It disables the currently displayed track when enabling another one.
It does work on Tizen 3 (tested with emulator) and Tizen 4 (tested on real TV).

One option is to use a custom element for subtitles, as on [webOS](https://github.com/jellyfin/jellyfin-web/blob/6ae494e07d3f1b119960e7878e56e5d6941f1904/src/plugins/htmlVideoPlayer/plugin.js#L1358-L1360). It may also be configurable: https://github.com/jellyfin/jellyfin-web/pull/5737

**Comment by Xcellion** [comment]
I just did that and rebuilt the app, but it doesn't seem to be working unfortunately. I checked and my TV is running Tizen 6. Not sure if that makes any difference.

I also added a line above `return true;` to `alert("test message")` and have confirmed that i built the app correctly and have pushed it to my TV

**Comment by Xcellion** [comment]
Nevermind I spoke too soon. I apparently edited the wrong line in the code. I edited the line you suggested and it works now:

`if (browser.tizenVersion >= 5 || browser.web0s)` <- this line

**Comment by Xcellion** [comment]
Do you know how to change the subtitle appearance? I changed it in the settings but it doesn't seem to be applying
