### ISSUE TITLE
Selection stuck in video alphabet index

### ISSUE THREAD

**Issue by kraftwerk2020** [jellyfin/jellyfin-tizen#316]
I'm guessing this is user error, but when I am in the video selection and remote into the alphabetical index on the left I can not get back out to select a video.  I have tried all of the remote buttons I can think of and nothing seems to work.

**Comment by dmitrylyzo** [comment]
On the left? Do you have a Right-to-Left language?

If not, you may have encountered https://github.com/jellyfin/jellyfin-tizen/issues/266

Also, if you have some custom CSS, it is better to try disabling it on the TV (Settings / Display / Disable server-provided custom CSS code).

**Comment by kraftwerk2020** [comment]
Thanks a ton, I think it is #266 I'll try the fix when I can.

**Comment by kraftwerk2020** [comment]
The fix in #266 worked to fix the layout, however when you navigate to the alphabet index on the left you can not navigate back out.  I'll close this issue and watch #266.  Thanks for the pointer.
