### ISSUE TITLE
Could we get a way to remember filters e.g. unwatched when re-opening the app or turning on the screen again?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [jellyfin/jellyfin-tizen#321]
Filter unwatched by default /remember previous filter used per user would be nice to have when reopening the screen.

**Comment by dmitrylyzo** [comment]
Filters should already be saved (per user, per device) in 10.10: https://github.com/jellyfin/jellyfin-web/pull/5717
What version of JellyfinWeb was used to build the app?

**Comment by LiamKarlMitchell** [comment]
Ah I used 10.9.11!
Thanks @dmitrylyzo , I'll have to have a bash at upgrading it

**Comment by LiamKarlMitchell** [comment]
Upgraded but it does not save the filters.
