### ISSUE TITLE
Can't Connect to the Server

### ISSUE THREAD

**Issue by xhivo97** [jellyfin/jellyfin-tizen#33]
I managed to successfully install the client app on my Samsung TV, it does open... However I can't connect to the jellyfin server, I tried to connect to the server from all my other devices including the TV's built-in web browser and they all connect to the server.

Where do I start troubleshooting something like this?

Thanks for all your hard work.

![IMG_20200612_005224](https://user-images.githubusercontent.com/35744300/84449303-4cd97380-ac4d-11ea-9154-83631fccfd7a.jpg)

**Comment by dmitrylyzo** [comment]
Try to prepend `http://`. We recently enabled `https://` by default.

**Comment by xhivo97** [comment]
@dmitrylyzo Tried that today and it worked. Thanks!
