### ISSUE TITLE
Samsung QN55Q6FNA double registration of directional inputs

### ISSUE THREAD

**Issue by Window-Hero** [jellyfin/jellyfin-tizen#36]
I have installed the client on a Samsung QN55Q6FNA, and whenever you input a direction on the remote that input is registered twice, causing you to select the menu item two entries over.  This makes menu navigation extremely tedious when there are an even number of entries, and impossible when there are an odd number.

**Comment by dmitrylyzo** [comment]
This should have been fixed once and for all by #30.
What `jellyfin-web` and` jellyfin-tizen` commits do you use?

**Comment by Window-Hero** [comment]
I don't have a record of that, but my files are all date stamped June 4, so I downloaded them shortly before that fix got merged.  I will recompile and report back.

**Comment by dmitrylyzo** [comment]
Windows?

**Comment by Window-Hero** [comment]
Yeah, I ran yarn on Linux and then pushed the files over to Windows for the final compile with Tizen Studio.

**Comment by dmitrylyzo** [comment]
If you do this from command line, then you should use `tizen.bat` instead of just `tizen`.

**Comment by Window-Hero** [comment]
Thanks, that was going to take me awhile to work back around to.

**Comment by Window-Hero** [comment]
This fixed it, thank you.  This is the first time a bug has ever been fixed in the time between me finding it, and me posting about it.

**Comment by dmitrylyzo** [comment]
Actually, first appearance of this issue was #4

**Comment by Window-Hero** [comment]
Yeah, I saw you reference it, I didn't catch that in my initial check of the issue tracker because the title wasn't clear, and it was far enough back that I didn't read the whole string.
