### ISSUE TITLE
remote control

### ISSUE THREAD

**Issue by dga4130-renato** [jellyfin/jellyfin-tizen#4]
Installed on 21/3 release of 2 feb.
remote controller navigation jumps two lines up -down left right.
even with keyboard, if you use arrows  will make impossible to select middle items.
no chance to get in settings menu also.

**Comment by dmitrylyzo** [comment]
Currently, master `jellyfin-web` build process is not polished - extra script injection occured. Working on this problem.

At the moment, you can remove this from `jellyfin-tizen/www/index.html` and build WGT only: `build-web` and `package`.
```html
    <!-- inject:js -->
            ...
    <!-- endinject -->
```

**Comment by dga4130-renato** [comment]
Will wait for a fix then

Il sab 21 mar 2020, 09:50 Dmitry Lyzo <notifications@github.com> ha scritto:

**Comment by dga4130-renato** [comment]
Hmm so I don't need to build web.. I just need to modify the latest tizen
before building the wdg right .. but before building I have to remove the
lines in the www dir .. html file .
Remove the lines inside the inject section right ? Then build

Il sab 21 mar 2020, 11:26 renato fabbeni <r.fabbeni@gmail.com> ha scritto:

**Comment by dmitrylyzo** [comment]
> Hmm so I don't need to build web.. I just need to modify the latest tizen before building the wdg right .. but before building I have to remove the lines in the www dir .. html file . Remove the lines inside the inject section right ? Then build

Yes.
Just modify html file, then build WGT.

**Comment by dga4130-renato** [comment]
Ok will test later . Thanks

Il sab 21 mar 2020, 17:37 Dmitry Lyzo <notifications@github.com> ha scritto:

**Comment by dga4130-renato** [comment]
confirm works, taking the line between 
    
            ...
    
and recompiling the wdg seems ok.

**Comment by G-eos** [comment]
Same for me, I confirm that the fix works. Thanks !

**Comment by iNfRaSoNiC13** [comment]
> Currently, master `jellyfin-web` build process is not polished - extra script injection occured. Working on this problem.
> 
> At the moment, you can remove this from `jellyfin-tizen/www/index.html`
> 
> ```
>     
>             ...
>     
> ```
> 
> and build WGT only: `build-web` and `package`.

I can confirm as well that this is working flawlessly, thank you.
