### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by garrit-schroeder** [jellyfin/jellyfin-tizen#40]
In the movies the search tab does not work. The TV Keyboard does not show when clicking on it.

**Comment by dmitrylyzo** [comment]
Probably `data-keyboard="false"` here https://github.com/jellyfin/jellyfin-web/blob/6139d936e2255f31567ca73ace38ed35536329cb/src/components/search/searchfields.template.html#L4

**Comment by Alcatraz077** [comment]
So I changed `data-keyboard` in my copy of `searchfields.template.html` to true in `jellyfin-web`, rebuilt `jellyfin-tizen`, and the wgt file. After deployment, it does work, but I'm not sure how `jellyfin-tizen` works with `jellyfin-web` so I'm not sure where to go from here.

**Comment by dmitrylyzo** [comment]
> From what I understand, jellyfin-tizen builds off of JF web as a wrapper of some sort?

Yes, it just runs jf-web.
You can open PR in `jellyfin-web` repo with those changes. Moreover, it will probably fix the same issue for webOS.
Not sure what to do with alpha picker below the search field.
