### ISSUE TITLE
The Pause/Play Button on the TV remote does not work.

### ISSUE THREAD

**Issue by garrit-schroeder** [jellyfin/jellyfin-tizen#41]
The pause/ play button does not worke. Instead the tv shows built in controls.
![15942247392847499345314730930870](https://user-images.githubusercontent.com/12541078/86943333-9f238c80-c146-11ea-9ce0-a5369fff96d1.jpg)

**Comment by dmitrylyzo** [comment]
This is how I wanted. Then you can push circle and OK to skip/pause/fastforward/rewind.

**Comment by garrit-schroeder** [comment]
Alright, I get it thanks. 

(Just my humble opinion: All other streaming service handle this feature differently. Like Netflix for example. So I would prefer the same experience better. 😋)

**Comment by dmitrylyzo** [comment]
Actually, Samsung's Checklist says that this button should exec Play/Pause, iirc. But then Non-smart Remote is more functional :man_shrugging: 
Moreover, using hint (this on-screen thing) you can also control Jellyfin's audio player.
