### ISSUE TITLE
Missing episodes not showed correctly

### ISSUE THREAD

**Issue by iNfRaSoNiC13** [jellyfin/jellyfin-tizen#42]
Hello,
can you please check why the missing episodes ( not aired ) cannot be viewed on jellyfin-tizen, on my Samsung TV there is not "i" button like in the web version.
Here are some image examples.
![1](https://user-images.githubusercontent.com/58333870/88140790-af317680-cbf2-11ea-8555-a98074820e6d.png)
![20200722_090811](https://user-images.githubusercontent.com/58333870/88140807-b8bade80-cbf2-11ea-9fa8-5e51222e1a61.jpg)
![20200722_090818](https://user-images.githubusercontent.com/58333870/88140820-bce6fc00-cbf2-11ea-91b6-a7830de052fa.jpg)

When click on the missing episode a message like the one showed in the pics is displayed.
Can you check it, thank you for your hard work.

**Comment by dmitrylyzo** [comment]
You probably just need to rebuild app with newer jellyfin-web.
There was `resume` action on item (initially there was no action at all). Now it is `link` in 10.6 (specifically jellyfin/jellyfin-web@3c37a57866a02ab3a7887f225ea0e79d51db9bf2).

**Comment by iNfRaSoNiC13** [comment]
> You probably just need to rebuild app with newer jellyfin-web.
> There was `resume` action on item (initially there was no action at all). Now it is `link` in 10.6 (specifically [jellyfin/jellyfin-web@3c37a57](https://github.com/jellyfin/jellyfin-web/commit/3c37a57866a02ab3a7887f225ea0e79d51db9bf2)).

My app was rebuilded 2 days ago but maybe there is a newer version already, thank you I will check it.
