### ISSUE TITLE
Cant open library after latest update

### ISSUE THREAD

**Issue by iNfRaSoNiC13** [jellyfin/jellyfin-tizen#44]
Hello,
I can't use the jellyfin-tizen app after the latest jellyfin update.
I can build the wgt file, install it and run it on my TV and my emulator but when I try to open the Library "Movies" (for example) 
I can open it but when I try to open some movie in there nothing happens. Its like the OK button is not pressed at all.
I've tried this on two separate samsung tvs + emulator from tizen - the issue is the same.
Please help. 
p.p The jellyfin server is working great on my browser.

**Comment by dmitrylyzo** [comment]
Yes, I found what is broken.
Fix: jellyfin/jellyfin-web#1731

**Comment by iNfRaSoNiC13** [comment]
@dmitrylyzo 
Thank you, I am very new here so I am not understanding everything but should I wait for this fix to be added to jellyfin-web?
Then clone it and proceed as usual?
Thank you for your hard work! I will donate here soon.

**Comment by dmitrylyzo** [comment]
> should I wait for this fix to be added to jellyfin-web?
> Then clone it and proceed as usual?

Yes, if you can wait. I think it will be merged quickly.
Also, if you can confidently use `git` and `patch`, you can apply patch to your cloned repo. Patch can be obtained from GH by appending `.diff` to PR's URL. You will got link https://patch-diff.githubusercontent.com/raw/jellyfin/jellyfin-web/pull/1731.diff
Just don't forget to reset/stash changes before pulling of updates.

**Comment by iNfRaSoNiC13** [comment]
> > should I wait for this fix to be added to jellyfin-web?
> > Then clone it and proceed as usual?
> 
> Yes, if you can wait. I think it will be merged quickly.
> Also, if you can confidently use `git` and `patch`, you can apply patch to your cloned repo. Patch can be obtained from GH by appending `.diff` to PR's URL. You will got link https://patch-diff.githubusercontent.com/raw/jellyfin/jellyfin-web/pull/1731.diff
> Just don't forget to reset/stash changes before pulling of updates.

Thank you, I will wait :)
