### ISSUE TITLE
HEVC (h265) dont rewind/fast forward

### ISSUE THREAD

**Issue by jasimancas** [jellyfin/jellyfin-tizen#49]
I have the latest version of this repo and the web repo (10.6.3) and when I try to rewind or fast forward a chapter of a series that is with HEVC codec it doesn't do anything, neither the buttons nor scrolling.

On web and Android it works fine.

If the file is 264 it works fine.

I have Tizen 5.5

**Comment by dmitrylyzo** [comment]
I made a HEVC test file without sound and seeking works fine on Tizen 4. I am using a simplified client that uses web directly from the server. So it is not 100% clean test, but fair enough.

How does your file play on web, Android and TV? DirectPlay/DirectStream/Transcode

**Comment by jasimancas** [comment]
I web Transcode and OK, in Android Transcode and OK.

In TV DirectPlay and bug

**Comment by Nazar78** [comment]
No issue here with Tizen 5.5 and JF 10.6.3 doing seeking in HEVC 100Mbps DirectPlay or Transcode/DirectStream. Maybe the JF logs could tell some hints.

**Comment by jasimancas** [comment]
Should I put the LOG in debug mode?
What tests can I do to make the log record changes?
This is my yesterday log, with tv show in 265 and 264.
[jellyfin20200817.log](https://github.com/jellyfin/jellyfin-tizen/files/5089914/jellyfin20200817.log)
