### ISSUE TITLE
Clarifications on how to install wgt to TV using Tizen IDE - Windows

### ISSUE THREAD

**Issue by maxiride** [jellyfin/jellyfin-tizen#74]
I've executed successfully all the steps to build the wgt file, however, I'm stuck at the last step: deploying it to the TV.

I'm on Windows 10 and there is no sdb command from the command prompt
```
'sdb' is not recognized as an internal or external command,
operable program or batch file.
```

so I am trying to install the wgt using the Tizen IDE, I successfully connected the TV (developer mode ON) but from the Wiki and the online resources I haven't managed to accomplish the task. In the Tizen ID I didn't find any menu or option to install wgt wirelessly.

**Comment by dmitrylyzo** [comment]
Specify the full path to `sdb`. On Linux, `sdb` is under `tizen-studio/tools`. On Windows it is probably the same.

To install from Studio, run/debug app from Studio. But in this case, you won't get log if installation failed, iirc.

**Comment by maxiride** [comment]
> Specify the full path to `sdb`. On Linux, `sdb` is under `tizen-studio/tools`. On Windows it is probably the same.
> 
> To install from Studio, run/debug app from Studio. But in this case, you won't get log if installation failed, iirc.

Oh thought it had been added to PATH. Thanks for pointing out the correct location.

I successfully connected to the TV, however, upon deploying the wgt a certificate error raised `Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>` But I should probably open a dedicated issue, I'll also look better if has already been assessed.

```
C:\Users\Federico\federicod\Projects\jellyfin\jellyfin-tizen>tizen.bat install -n Jellyfin.wgt -t QE50Q60TAUXZT
Transferring the package...
Transferred the package: C:\Users\Federico\federicod\Projects\jellyfin\jellyfin-tizen\Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[10]
app_id[AprZAARz4r.Jellyfin] installing[13]
app_id[AprZAARz4r.Jellyfin] installing[15]
app_id[AprZAARz4r.Jellyfin] installing[18]
app_id[AprZAARz4r.Jellyfin] installing[21]
app_id[AprZAARz4r.Jellyfin] installing[23]
app_id[AprZAARz4r.Jellyfin] installing[26]
app_id[AprZAARz4r.Jellyfin] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [6880]ms
Failed to install Tizen application.
Total time: 00:00:16.972

```

**Comment by dmitrylyzo** [comment]
I saw this error from one user: https://github.com/jellyfin/jellyfin-tizen/issues/10#issuecomment-615578457 But that was emulator.

1. Make sure you have built app with Samsung certifiacate (should be marked :white_check_mark: in Certificate Manager).
2. Try to `Permit to install applications` (from context menu on your TV in Device Manager).

**Comment by maxiride** [comment]
Thanks for following through.

- The certificate is checked and active
- I've redone the `Permit to install applications` and the process terminates with a successful message.

When creating the certificate, however, the process asked me to input DUID of the devices where I want to make the certificate valid, the DUID present matches the one of the TV obtained from the Device Manager.

**Comment by maxiride** [comment]
Solved 🚀🚀

The issue I had was that in the process of attempting this whole DIY app install I built the jellyfin wgt with a certificate, later on I deleted the certificate and made a new one. I thought to have messed up other steps.
So the certificated uploaded to the TV and the one used to sign the wgt were different:

- I deleted all the certificates I made
- I made a new certificate
- Built the wgt with the new certificate
- pushed this new certificate to the tv
- executed again the deploy command

**Comment by philippemiron** [comment]
@maxiride could you add a bit more details on each of those steps?
