### ISSUE TITLE
Cant change server

### ISSUE THREAD

**Issue by mrzav** [jellyfin/jellyfin-tizen#75]
After changing to a new local server on a new ip the tizen app stopped working. When i opened it, it just keep loading forever without prompting me to choose the new server's ip. In the global app menu when I click on details it says that servers are under maintenance.

**Comment by dmitrylyzo** [comment]
Server info is stored in local storage (`jellyfin_credentials`).
You can uninstall and reinstall app to clear local storage - but you will lose some user settings.
Or try build app with jf-web PR jellyfin/jellyfin-web#2558 - you should be redirected to the server selection page where you can remove and re-add the server.

**Comment by mrzav** [comment]
Thank you very much for the swift response! Is there a way to clear local storage without reinstalling the app? I no longer have the setup which i used to install it and I remember it was quite a pain to do it. Also any eta on when the app will be available directly on the tizen store?

**Comment by dmitrylyzo** [comment]
> Is there a way to clear local storage without reinstalling the app?

I didn't find any other way.

Is your server the same (id, users) but with a new IP?
If so, perhaps you can temporary set it to an old IP, connect with app, logout, change server and remove server from the server select page, then unset old IP. This way you will remove it from `jellyfin_credentials`.

> Also any eta on when the app will be available directly on the tizen store?

No ETA. As you can see, there are bugs.

**Comment by olivercastle** [comment]
This is resolved using this PR - [https://github.com/jellyfin/jellyfin-apiclient-javascript/pull/187](https://github.com/jellyfin/jellyfin-apiclient-javascript/pull/187)

I couldn't resolve the issue by deleting and reinstalling the App on my TV. The previous server details seemed to persist.

I'd close this issue in favour of that PR.

**Comment by mrzav** [comment]
I see that the issued is apparently resolved in this: [jellyfin-apiclient-javascript](https://github.com/jellyfin/jellyfin-apiclient-javascript).
Is the build process described in the main page still correct? I'm confused because it doesn't appear to use the repo with the fix but just [jellyfin-tizen](https://github.com/jellyfin/jellyfin-tizen) and [jellyfin-web](https://github.com/jellyfin/jellyfin-web).

**Comment by dmitrylyzo** [comment]
@mrzav We need to release `jellyfin-apiclient-javascript` and update its version in `jellyfin-web/package.json`.

However, you can redirect `jellyfin-apiclient-javascript` to its repo in `jellyfin-web/package.json`.
At https://github.com/jellyfin/jellyfin-web/blob/ab9bc8185ffa721db26a49d091ba20a163510c6a/package.json#L67
change to `"jellyfin-apiclient": "https://github.com/jellyfin/jellyfin-apiclient-javascript.git",`
then `npm i --no-audit` -> you will get `dist` with those changes.

**Comment by mrzav** [comment]
@dmitrylyzo I finally managed to find time to rebuild the app so i can close the issue, however I forgot how I did last time. I think i have the correct certificate in the tizen studio ide but i dont know how to build the wgt file and/or how to import the files I made in the previous steps in the tizen studio software. If i run:
`tizen build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock"`
it just opens tizen studio and it doesn't seem to do anything.

**Comment by mrzav** [comment]
Nevermind i solved my previous issue. However now when i run
`tizen build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock"`
it stops with an error:
In tizen.js file, line 4, char 5: 'console' is undefined

**Comment by dmitrylyzo** [comment]
https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Windows#build-wgt
> tizen.bat ...

Its path should be added to `PATH` environment variable, or just run with its full path.

**Comment by mrzav** [comment]
> https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Windows#build-wgt
> 
> > tizen.bat ...
> 
> Its path should be added to `PATH` environment variable, or just run with its full path.

tizen.bat file doesn't seem to exist anywhere in my system. The most similar thing is TizenStudio.bat in one of the Tizen studio directories.
If i run:
`tizen.bat build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock"`
I get tizen.bat not recognized error as expected since it doesnt seem to exist anywhere and so i cant add it to the path variable.
If I run:
`tizen build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock"`
whitout the .bat, It appears to do something but than it crashes with the error:
In tizen.js file, line 4, char 5: 'console' is undefined, code:800A1391, source: Microsoft jScript runtime error

**Comment by dmitrylyzo** [comment]
It should be in `tizen-studio/tools/ide/bin`.
`tizen` just runs `tizen.js`, which we don't want.

**Comment by mrzav** [comment]
@dmitrylyzo Thank you very much for your assistance, I try to find it using the windows search tool but it's just so unreliable.
I manage to finally install it on my tv and everything is working as intended.
If i take down my server after a while i get redirected to a server selection page.
You may consider to add the instructions to deploy on tv here [https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Windows](https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Windows) since i think you need to use the `tizen.bat` command instead of  `tizen` as is written on the main page.
Cheers, and keep up the awesome job! <3
