### ISSUE TITLE
Black screen when launching the Jellyfin app

### ISSUE THREAD

**Issue by wjbeckett** [jellyfin/jellyfin-tizen#8]
Hi,
I have successfully compiled and built the Jellyfin.wgt and it installs fine on my TV however, when I launch the app I just get a black screen. No matter how long I leave it there for, nothing happens.

My TV is a UA55MU7000.

Any help would be greatly appreciated.

**Comment by dmitrylyzo** [comment]
If I am right, UA55MU7000 is Tizen 3.
You can try changes from this PR https://github.com/jellyfin/jellyfin-web/pull/1026

**Comment by wjbeckett** [comment]
@dmitrylyzo That has indeed fixed it.
Thank you.
Just need to apply the double line jump patch as well.
