### ISSUE TITLE
install for tizen

### ISSUE THREAD

**Issue by persona-ny** [jellyfin/jellyfin-tizen#87]
Can anyone write a normal instruction how to install it on a TV ?????????
I can not understand!!!! I have windows

**Comment by dmitrylyzo** [comment]
Which step do you not understand?

**Comment by persona-ny** [comment]
I don't understand what to do after creating a certificate in tizen

**Comment by dmitrylyzo** [comment]
FYI, there is a build instruction for Windows: https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Windows
_But it is almost the same as for Linux_

Suppose you are going to build an app in `C:\jellyfin`.
1. Create `jellyfin` folder on `C:` disk.
2. Run `Windows Command Prompt`.
3. In the command line: `cd C:\jellyfin`
4. Execute command from step 5: `git clone https://github.com/jellyfin/jellyfin-web.git`
_you will get `jellyfin-web` sources_
5. Execute command from step 6: `git clone https://github.com/jellyfin/jellyfin-tizen.git`
_you will get `jellyfin-tizen` sources_

Next, perform the remaining steps in order: `Build Jellyfin Web`, `Prepare Interface`, `Build WGT`.
In the last step you may have a problem running `tizen.bat` if it is not added to the `PATH`.

**Comment by persona-ny** [comment]
![Снимок экрана (2)](https://user-images.githubusercontent.com/70141403/120108637-83224280-c17f-11eb-8b35-f9578d1bab83.png)

**Comment by dmitrylyzo** [comment]
With NodeJS 14, I have no error.

**Comment by 3nprob** [comment]
> ![Снимок экрана (2)](https://user-images.githubusercontent.com/70141403/120108637-83224280-c17f-11eb-8b35-f9578d1bab83.png)

Looks like it's running out of memory as it's running. If closing some applications (esp browsers) doesn't help, either something else is wrong or you need more RAM.
