### ISSUE TITLE
Tracking Progress for Samsung Submission

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-tizen#94]
This is a general issue for tracking progress in Samsung submission.

It will be updated soon with steps and information on what testing and changes need to be made in order for submission to pass.

Also a small reminder that the branding guidelines apply: https://jellyfin.org/docs/general/contributing/branding.html#usage-of-the-jellyfin-name

**Comment by afsilvasantos** [comment]
Do you have some sort of predicted release date for tizen?

**Comment by kaphwor** [comment]
Interested to know too. I've installed this on my TV and it's game changing! Works perfectly, way faster than casting and I believe all Samsung users would love to be able to use it.
Considering making contributions to this project but my know how on TV development and front end is somewhat rudimental 😅

**Comment by mjeshurun** [comment]
I agree. The Jellyfin Tizen app works great on my 2019 Frame. 
The only small change I would suggest is to enlarge the app's "home screen" shortcut icon to be the same rectangular size as all other shortcut icons.

**Comment by anthonylavado** [comment]
To answer a few questions…

Release date? Nothing set at this time. All the documentation I've got is for the LG webOS stuff right now, so I haven't had a chance to look at the Samsung submission requirements. I've also just had my main computer's hard drive die on me, so that is slowing things down (it's an iMac).

Right now I think we'll try to make an "official" USB auto install version, and take issues/fixes until I can get back into certification testing for this and the LG app.

**Comment by gugiola** [comment]
"Right now I think we'll try to make an "official" USB auto install version, and take issues/fixes until I can get back into certification testing for this and the LG app." any news when  USB auto install version will be available? 
Thanks, for you work!

**Comment by gardner** [comment]
Can I help by taking this task on @anthonylavado ?

How do we create a Jellyfin organisation? Is there a legal entity? Should I just publish it under my name?

**Comment by anthonylavado** [comment]
@gardner We have one, including an existing relationship with our regional Samsung Content Manager.
My energy has been focused on the webOS release for right now, which has been largely waiting for 10.8 to hit beta with a few different features in mind (it's now been a year since we made a big release). As soon as I finish getting that over the line to LG (at which point it's out of my hands), then I can come back to this.

It will be soon. We get closer now that we have the 10.8 beta.

**Comment by grayran** [comment]
@anthonylavado If there are any items I can pick up to keep this moving let me know!

**Comment by nullasaservice** [comment]
Any news on this issue? Anything that can be done by contributors?

**Comment by anthonylavado** [comment]
The best question I can ask: How well is it working right now?

**Comment by therhenals** [comment]
> The best question I can ask: How well is it working right now?

Hello, the truth is that the app works perfectly, I installed it on my Samsung TV and frankly I was surprised that I came from Android TV. I would like to know how this process is going and to know if it is possible to contribute in some way.

**Comment by zLupa** [comment]
> The best question I can ask: How well is it working right now?

It's working perfectly, I had no issues, maybe just installing it was kind of a pain in the ass but this issue is going to solve it.

**Comment by jolarsso** [comment]
I would also love to have this installable from the Samsung app store! I'm currently using infuse for Apple TV bur would prefer to stream natively and not have to juggle two remotes to get my media going :)

**Comment by Azulath** [comment]
Is there any more information regarding the state of the submission or anything like that?

**Comment by gugiola** [comment]
At this point it would be sufficient to install at least via USB.

**Comment by MagicTrevor** [comment]
Is it possible to have a prebuilt binary to test with? Or was this going to be submitted soon now that the LG release has been out?

**Comment by oysstu** [comment]
> Is it possible to have a prebuilt binary to test with?

I've been using the releases from the following repo. Works great.
https://github.com/jeppevinkel/jellyfin-tizen-builds

**Comment by MagicTrevor** [comment]
> > Is it possible to have a prebuilt binary to test with?
> 
> 
> 
> I've been using the releases from the following repo. Works great.
> 
> https://github.com/jeppevinkel/jellyfin-tizen-builds

Oh that's awesome! Thanks for sharing!

**Comment by jolarsso** [comment]
> > Is it possible to have a prebuilt binary to test with?
> 
> I've been using the releases from the following repo. Works great. https://github.com/jeppevinkel/jellyfin-tizen-builds

That's fantastic. Thanks!

**Comment by oysstu** [comment]
> Is there a benefit for using the releases in jeppevinkel's github project vs the releases in this project?

Not really, it just automates the build process and uploads the binaries to github

**Comment by mjeshurun** [comment]
> Not really, it just automates the build process and uploads the binaries to github

Thank you :)
I'm trying to understand if I'll gain any benefit from reinstalling the jellyfin.wgt app using jeppevinkel's latest stable release?
I installed Jellyfin Tizen on my Samsung tv a year ago using the official Jellyfin github release and I have not updated it since.
From the release history in jeppevinkel github's page it looks like there were a few updates in the past year (latest one is for jellyfin-web 1.8.7). 
As such, will I gain any benefit reinstalling the Jellyfin Tizen app using jeppevinkel's method? 
Will it update my current Jellyfin Tizen app to version 1.8.7?

**Comment by oysstu** [comment]
> As such, will I gain any benefit reinstalling the Jellyfin Tizen app using jeppevinkel's method? 
It simply pulls the latest release of jellyfin-web and builds it for tizen using the master branch of this repo. No changes to the overall version or build process. Consult the changelogs for jellyfin-web if it makes sense to update.

> Will it update my current Jellyfin Tizen app to version 1.8.7?
You may have to uninstall the installed version first, but yes.

**Comment by zLupa** [comment]
> > The best question I can ask: How well is it working right now?
> 
> It's working perfectly, I had no issues, maybe just installing it was kind of a pain in the ass but this issue is going to solve it.

You can't adjust the subtitle offset

**Comment by mjeshurun** [comment]
> You can't adjust the subtitle offset

Subtitles offset is working properly for me.

**Comment by SchoolGuy** [comment]
@anthonylavado Is there a status update since march? Considering that the Tizen Studio is only working on Ubuntu/Windows/MacOS properly, it would be much easier to just install it from the Appstore... :)

**Comment by anthonylavado** [comment]
Nothing to Samsung yet, but there's gonna be a post with specific points people can help with soon. Gonna try to put it up tonight/tomorrow.

**Comment by afsilvasantos** [comment]
Hi there.
Isn’t there a way to install it without store? For example, smart iptv app you just plug in a usb stick containing the packaged file and the tv will install it. Would it be possible to with each release provide that package?

**Comment by Georift** [comment]
I made a script that should be able to install the latest development build of `jellyfin-tizen` pretty quickly on a TV:

```bash
# ensure your TV is in developer mode, then run:
docker run --rm georift/install-jellyfin-tizen <samsung tv ip>
```

More detailed instructions can be found here [found here](https://github.com/Georift/install-jellyfin-tizen).

**Comment by jolarsso** [comment]
This is even better. For the *really* lazy ones among us. Now I might even get to trying it :)

Thanks!

**Comment by kiloPause** [comment]
any plan when jellyfin can be installed just from from usb (as emby)?

**Comment by bsod-haunted** [comment]
Hi,
I did not previously use Jellyfin, because there was no Tizen app. Since i now found this thread with a link to prebuild binarys, I decided to give it a shot.
Unfortunately I have to report, that for my usecase Jellyfin currently does not work.
In my test, an MKV container with an H.265 4k movie is not natively supported on my TV, causing Jellyfin to start transcoding. This however does not work, because the "server" does not have enough resources to do that.
With Plex (running on the same hardware), this is a non issues because on the same TV the same files playes just fine without transcoding the movie.

This is unfortunate, because I really want to get rid of plex. Otherwise, i really like Jellyfin for its UI, the responsivenes (if it does not transcode) and available features. One that i really like is that it tells you why it is transcoding something.

If there is any information that i can provide for the developers that are helpful, I will happily do so.
My tests were done with Jellyfin v10.8.8 [from this repo](https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2022-12-05) on an 4k TV from 2021.

Best regards, and happy holidays

**Comment by nibble** [comment]
Unfortunately, Jellyfin intend to transcode too much using the Tizen app. I have yet to find any H.265 4k MKV file that can't directly be played by my Samsung TV. I suggest to disable video transcoding for the user (Dashboard, Users, Open user, Media Content, uncheck Allow video playback that requires transcoding). It may solve your problems, @bsod-haunted. I'm not sure who is the culprit here, maybe the Tizen Jellyfin app needs to better report the capabilities of the device.

**Comment by dmitrylyzo** [comment]
@bsod-haunted Look in `Playback Info` (the gear button in the player) or in the Dashboard (on the PC) for the reason of transcoding.
_Open a new issue so as not to disturb others._

<details>
<summary>
For the record, this plays direct on NU7400 (Tizen 4) via the app:

_I use unstable server and unstable jf-web (there are currently issues with restoring views and exiting the application)._
</summary>

```
General
Unique ID                                : 96780592507409395921192224999239330731 (0x48CF439D02F3DD5CF581EEB3B5402BAB)
Complete name                            : Chameleon-4k-hevc10hdr10_copy-dd+.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 236 MiB
Duration                                 : 30 s 114 ms
Overall bit rate                         : 65.8 Mb/s
Writing application                      : Lavf58.20.100
Writing library                          : Lavf58.20.100
ErrorDetectionType                       : Per level 1

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 30 s 114 ms
Bit rate                                 : 64.5 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.324
Stream size                              : 231 MiB (98%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 60 cd/m2

Audio
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced Audio Coding 3
Format profile                           : E-AC-3+Atmos / E-AC-3
Codec ID                                 : A_EAC3
Duration                                 : 30 s 16 ms
Bit rate mode                            : Constant
Bit rate                                 : 500 b/s
Channel(s)                               : 8 channels
Channel(s)_Original                      : 15 objects / 6 channels
Channel positions                        : 15 objects / Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 187.500 FPS (256 SPF)
Bit depth                                : 32 bits
Compression mode                         : Lossy
Stream size                              : 1.83 KiB (0%)
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
```
</details>

**Comment by bsod-haunted** [comment]
@nibble 
Thank you very much! This workaround makes playback possible on my tv.

@dmitrylyzo 
as requested, i opened a [new issue](https://github.com/jellyfin/jellyfin-tizen/issues/163) and added the information.

**Comment by TomasMonkevic** [comment]
What are the current blockers to releasing the app? If you need any help I'm willing to contribute

**Comment by Georift** [comment]
> I made a script that should be able to install the latest development build of `jellyfin-tizen` pretty quickly on a TV:
> 
> ```bash
> # ensure your TV is in developer mode, then run:
> docker run --rm georift/install-jellyfin-tizen <samsung tv ip>
> ```
> 
> More detailed instructions can be found here [found here](https://github.com/Georift/install-jellyfin-tizen).

I've opened a PR to include these instructions in the main readme, it could be a nice step to help users install while we wait for an official build.

Throwing a thumbs up on [this PR](https://github.com/jellyfin/jellyfin-tizen/pull/170) might be nice to show people are interested and help it get merged.

**Comment by bdovaz** [comment]
Any news? Need help?

Thank you!

**Comment by kraM1tt** [comment]
Yeah would be awesome if you guys could get it on the Tizen store! I know a lot of people stalling the switch over to Jellyfin just because they want to use their Samsung TV like they do with Plex

**Comment by mrkesu** [comment]
An official Tizen version would be great.

The reason I would love a native version instead of running it from my Chromecast is because my TV supports Dolby Atmos, but it does not support Atmos redirection. In short, it means only "native apps" will output Dobly Atmos, but anything plugged in to the TV will not use Atmos 😅

**Comment by itsmejoeeey** [comment]
> Nothing to Samsung yet, but there's gonna be a post with specific points people can help with soon. Gonna try to put it up tonight/tomorrow.

Hi @anthonylavado, it's been more than 9 months since the last update - can you please advise how we can contribute to getting this across the line?

**Comment by gardner** [comment]
I am keen to help out if you are too busy @anthonylavado

**Comment by anthonylavado** [comment]
Sorry to close this off in an abrupt fashion, but putting updates here notifies **a lot of people.**

I have created a new issue for release tracking. You can see it here: https://github.com/jellyfin/jellyfin-tizen/issues/222

If you want, you can follow along by reacting to that top comment using the reaction button, or clicking/tapping Subscribe.

I would ask that you please do not post in that issue, again, to avoid notifying people for no reason. If we need specific assistance on something, we'll create a comment linking to an adjacent issue where we can discuss further.

Thank you for all your patience folks. This is the next step in what I like to call "meeting you where you are". Let's try and get this over the line before December 8th.
