### ISSUE TITLE
Cannot install on UE43MU6172

### ISSUE THREAD

**Issue by jiriks74** [jellyfin/jellyfin-tizen#95]
Hi, 
I fér following output, when I try to upload to my Samsung TV:

<details>

```
Transferring the package...
Transferred the package: C:\Users\jiris\Documents\jellyfin-tizen\Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin

package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt

was_install_app return WAS_TRUE

app_id[AprZAARz4r.Jellyfin] install start

app_id[AprZAARz4r.Jellyfin] installing[8]

app_id[AprZAARz4r.Jellyfin] installing[11]

app_id[AprZAARz4r.Jellyfin] installing[14]

app_id[AprZAARz4r.Jellyfin] installing[17]

app_id[AprZAARz4r.Jellyfin] installing[20]

app_id[AprZAARz4r.Jellyfin] installing[22]

app_id[AprZAARz4r.Jellyfin] install failed[118]

spend time for wascmd is [4165]ms

cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:06.643
```
</details>

I Havel created a certificate, I have the tv in developer mode with my PC up set, I have the tv in device manager. Also, I get `org.tizen.sdblib.exception.SdbCommandRejectedException: closed` if I try to install via device manager.

**Comment by dmitrylyzo** [comment]
> I fér following output, when I try to upload to my Samsung TV:

Have you run `Permit to install applications` (in Device Manager) to install certificate on your TV?
Some info about `118`: https://developer.youi.tv/5.7/Content/Tizen_DevTopics/H1BuildingInstallingAppWidgets.htm

> Also, I get `org.tizen.sdblib.exception.SdbCommandRejectedException: closed` if I try to install via device manager.

After several attempts to install the app via Device Manager, I gave up and only use CLI.

**Comment by jiriks74** [comment]
Do you know the feeling, when you ask for help and just minutes before someone answers, you figure it out? I swear that when I got notification for your comment, the installation successfully finished.

Yes, it was indeed this issue, thanks for your quick reply, I will close this issue as it is resolved.
