### ISSUE TITLE
Build Jellyfin.wgt file using mac

### ISSUE THREAD

**Issue by mjeshurun** [jellyfin/jellyfin-tizen#96]
Hi all, 
I'm trying to install the Jellyfin Tizen app on my Samsung Frame TV.
I followed the steps to install Tizen Studio, Certificate Manager, I added my TV as a device, and I created a certificate. 
I also followed the Jellyfin installation steps listed in this Github projecrt to create the jellyfin-web and jellyfin-tizen folders.
However, I'm stuck on the step to create the Jellyfin.wgt file. 

In what folder and with what commands should I create the Jellyfin.wgt file? 
I tried to run these commands in the jellyfin-tizen folder using terminal:

`tizen build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock"
tizen package -t wgt -o . -- .buildResult`

but I got error messages.

I could use some help with this step.
Thank you very much.

**Comment by dmitrylyzo** [comment]
This command should be called in the `jellyfin-tizen`.

Probably the path of `tizen` is not in the `PATH` variable. Try specifying the full path, e.g. `tizen-studio/tools/ide/bin/tizen`.

**Comment by mjeshurun** [comment]
> This command should be called in the `jellyfin-tizen`.
> 
> Probably the path of `tizen` is not in the `PATH` variable. Try specifying the full path, e.g. `tizen-studio/tools/ide/bin/tizen`.


Thank you very much! 
With your help I managed to build the Jellyfin.wgt file. The file was created inside the jellyfin-tizen folder.
I then Imported the Jellyfin.wgt file in the Tizen Studio app as a web application. I converted the imported project using the Tizen Convert Wizard to a tv-samsung profile. And then I tried to run the project as a Tizen Web Application.
However, I'm seeing the process stuck on "Launching Jellyfin: (22%)".
Have I done something wrong?

**Comment by mjeshurun** [comment]
Had to reinstall the jellyfin app, so I figured I'd share the exact command I needed to use to create the jellyfin.wgt file.
Hope this helps others. 

```
[full path tizen-studio/tools/ide/bin folder]/tizen build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock"
[full path tizen-studio/tools/ide/bin folder]/tizen package -t wgt -o . -- .buildResult
```

*to get the full path of the `tizen-studio/tools/ide/bin` folder, open the folder in terminal and type the command `pwd`.
This will give you the full path.
